## 2026 MIAMI GRAND PRIX — PODIUM PREDICTION
### Rolling data: Australia (R1) + China (R2) + Japan (R3), Miami qualifying grid + weather sourced live (May 2026) - update to readme

In [19]:
# Importing the necessary libraries
import pandas as pd
import numpy as np
 
from sklearn.linear_model import Ridge, ElasticNet
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import LeaveOneOut
from sklearn.impute import SimpleImputer
from xgboost import XGBRegressor

### Pulling requests from Fast F1 API

In [ ]:
import sys
print(sys.executable)

/usr/bin/python3

In [ ]:
import sys
!{sys.executable} -m pip install fastf1

Collecting fastf1
  Downloading fastf1-3.8.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: cryptography in /usr/local/lib/python3.12/dist-packages (from fastf1) (43.0.3)
Requirement already satisfied: matplotlib<4.0.0,>=3.8.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (3.10.0)
Requirement already satisfied: numpy<3.0.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.0.2)
Requirement already satisfied: pandas<3.0.0,>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.2.2)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from fastf1) (4.9.6)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.12.3)
Requirement already satisfied: pyjwt in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.12.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.9.0.post0)
Collecting rapidfuzz (from fastf1)
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Collecting requests-cache>=1.0.0 (from fastf1)
  Downloading requests_cache-1.3.1-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: requests>=2.30.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.32.4)
Requirement already satisfied: scipy<2.0.0,>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (1.16.3)
Collecting signalrcore (from fastf1)
  Downloading signalrcore-1.0.2-py3-none-any.whl.metadata (13 kB)
Collecting timple>=0.1.6 (from fastf1)
  Downloading timple-0.1.8-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: websockets>=10.3 in /usr/local/lib/python3.12/dist-packages (from fastf1) (15.0.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.1.1->fastf1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.1.1->fastf1) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->fastf1) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (2026.2.25)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache>=1.0.0->fastf1) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache>=1.0.0->fastf1)
  Downloading cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Collecting url-normalize>=2.0 (from requests-cache>=1.0.0->fastf1)
  Downloading url_normalize-2.2.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography->fastf1) (2.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (0.4.2)
Requirement already satisfied: msgpack==1.1.2 in /usr/local/lib/python3.12/dist-packages (from signalrcore->fastf1) (1.1.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography->fastf1) (3.0)
Downloading fastf1-3.8.2-py3-none-any.whl (135 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.4/135.4 kB 5.6 MB/s eta 0:00:00
Downloading requests_cache-1.3.1-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.2/70.2 kB 6.1 MB/s eta 0:00:00
Downloading timple-0.1.8-py3-none-any.whl (17 kB)
Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 62.9 MB/s eta 0:00:00:00:01
Downloading signalrcore-1.0.2-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.6/55.6 kB 4.1 MB/s eta 0:00:00
Downloading cattrs-26.1.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 6.4 MB/s eta 0:00:00
Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Installing collected packages: url-normalize, signalrcore, rapidfuzz, cattrs, requests-cache, timple, fastf1
Successfully installed cattrs-26.1.0 fastf1-3.8.2 rapidfuzz-3.14.5 requests-cache-1.3.1 signalrcore-1.0.2 timple-0.1.8 url-normalize-2.2.1

In [ ]:
import fastf1
import pandas as pd

import numpy as np
import os

In [ ]:
# ── Load the session ──────────────────────────────────────────────────────────
session = fastf1.get_session(2026, "Japan", "Q")
session.load(telemetry=False, weather=True, messages=False)

laps = session.laps

req         WARNING 	DEFAULT CACHE ENABLED! (24.0 KB) /root/.cache/fastf1
WARNING:fastf1.fastf1.req:DEFAULT CACHE ENABLED! (24.0 KB) /root/.cache/fastf1
core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.8.2]
INFO:fastf1.fastf1.core:Loading data for Japanese Grand Prix - Qualifying [v3.8.2]
req            INFO 	No cached data found for session_info. Loading data...
INFO:fastf1.fastf1.req:No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
INFO:fastf1.api:Fetching session info data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
INFO:fastf1.fastf1.req:No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
INFO:fastf1.api:Fetching driver list...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
INFO:fastf1.api:Fetching session status data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
INFO:fastf1.api:Fetching track status data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
INFO:fastf1.api:Fetching timing data...
_api           INFO 	Parsing timing data...
INFO:fastf1.api:Parsing timing data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
INFO:fastf1.api:Fetching timing app data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
core           INFO 	Processing timing data...
INFO:fastf1.fastf1.core:Processing timing data...
req            INFO 	No cached data found for weather_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
INFO:fastf1.api:Fetching weather data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['12', '63', '81', '16', '1', '44', '10', '6', '5', '41', '3', '31', '27', '30', '43', '55', '23', '87', '11', '77', '14', '18']
INFO:fastf1.fastf1.core:Finished loading data for 22 drivers: ['12', '63', '81', '16', '1', '44', '10', '6', '5', '41', '3', '31', '27', '30', '43', '55', '23', '87', '11', '77', '14', '18']

In [ ]:
# ── Best individual sector times per driver (ultimate lap) ────────────────────
# FastF1 stores sector times as timedeltas — convert to seconds
def td_to_s(td):
    """Convert timedelta (or NaT) to float seconds."""
    if pd.isnull(td):
        return np.nan
    return td.total_seconds()

records = []
for driver in laps["Driver"].unique():
    drv_all = laps.pick_drivers(driver).pick_wo_box()
    
    if drv_all.empty:
        continue  # skip drivers with no valid laps

    best_s1 = drv_all["Sector1Time"].dropna().min()
    best_s2 = drv_all["Sector2Time"].dropna().min()
    best_s3 = drv_all["Sector3Time"].dropna().min()
    best_lap = drv_all["LapTime"].dropna().min()  # ← get best lap directly

    records.append({
        "Driver":    driver,
        "S1":        td_to_s(best_s1),
        "S2":        td_to_s(best_s2),
        "S3":        td_to_s(best_s3),
        "BestLap_s": td_to_s(best_lap),
    })

quali_df = pd.DataFrame(records)

# ── Ultimate lap = S1 + S2 + S3 ───────────────────────────────────────────────
quali_df["UltimateLap_s"] = (
    quali_df["S1"] + quali_df["S2"] + quali_df["S3"]
).round(3)

# ── Gap from pole (use best Q3 / overall best lap) ───────────────────────────
pole_time = quali_df["BestLap_s"].min()
quali_df["JapanGapFromPole_s"] = (quali_df["BestLap_s"] - pole_time).round(3)

# Percentage gap — more comparable across circuits than raw seconds
quali_df["JapanGapFromPolePct"] = (
    quali_df["JapanGapFromPole_s"] / pole_time * 100
).round(4)

# ── Grid position (sort by best lap) ─────────────────────────────────────────
quali_df = quali_df.sort_values("BestLap_s").reset_index(drop=True)
quali_df["JapanGrid"] = quali_df.index + 1

# Adding The tremperature + rainfall probability on that day
# Japan GP weather — sourced manually (e.g. Weather.com / AccuWeather)
rain_probability = 0.10   # replace with actual figure
temperature      = 18.0   # replace with actual figure

quali_df["RainProbability"] = rain_probability
quali_df["Temperature"]     = temperature

# Adding the Driver points from the 2 races(Australia and Chinese GPs)
driver_points = {
    "RUS": 44, "LEC": 38, "ANT": 35, "NOR": 32, "HAM": 28,
    "PIA": 22, "VER": 18, "BEA": 14, "LIN": 12, "BOR": 10,
    "GAS": 8,  "LAW": 6,  "OCO": 4,  "ALB": 4,  "HAD": 2,
    "COL": 1,  "SAI": 0,  "ALO": 0,  "BOT": 0,
    "STR": 0,  "PER": 0,  "HUL": 0,
}

max_driver_pts = max(v for v in driver_points.values() if v > 0)
quali_df["DriverPoints"]     = quali_df["Driver"].map(driver_points).fillna(0)
quali_df["DriverPointsNorm"] = (quali_df["DriverPoints"] / max_driver_pts).round(4)


print(quali_df[["Driver", "S1", "S2", "S3", "UltimateLap_s",
                "BestLap_s", "JapanGrid", "JapanGapFromPole_s",
                "JapanGapFromPolePct", "RainProbability", "Temperature", "DriverPointsNorm"]])

quali_df.to_csv("japan_quali.csv", index=False)
print("\nSaved → japan_quali.csv")

   Driver      S1      S2      S3  UltimateLap_s  BestLap_s  JapanGrid  \
0     ANT  31.827  39.398  17.464         88.689     88.778          1
1     RUS  31.782  39.607  17.616         89.005     89.076          2
2     PIA  31.954  39.557  17.577         89.088     89.132          3
3     LEC  31.655  39.855  17.668         89.178     89.303          4
4     NOR  32.049  39.716  17.627         89.392     89.409          5
5     HAM  31.762  39.933  17.625         89.320     89.567          6
6     GAS  32.143  40.029  17.519         89.691     89.691          7
7     HAD  32.164  40.094  17.608         89.866     89.978          8
8     BOR  32.288  40.149  17.492         89.929     89.990          9
9     LIN  32.548  40.043  17.501         90.092     90.109         10
10    VER  32.369  40.196  17.565         90.130     90.262         11
11    OCO  32.481  40.048  17.700         90.229     90.309         12
12    HUL  32.400  40.181  17.564         90.145     90.358         13
13    LAW  32.791  40.175  17.529         90.495     90.495         14
14    COL  32.463  40.433  17.610         90.506     90.627         15
15    SAI  32.844  40.434  17.576         90.854     90.927         16
16    ALB  32.858  40.489  17.741         91.088     91.088         17
17    BEA  32.824  40.421  17.845         91.090     91.090         18
18    PER  33.512  40.667  18.027         92.206     92.206         19
19    BOT  33.362  40.961  17.947         92.270     92.330         20
20    ALO  33.536  41.206  17.904         92.646     92.646         21
21    STR  33.595  41.341  17.948         92.884     92.920         22

    JapanGapFromPole_s  JapanGapFromPolePct  RainProbability  Temperature  \
0                0.000               0.0000              0.1         18.0
1                0.298               0.3357              0.1         18.0
2                0.354               0.3987              0.1         18.0
3                0.525               0.5914              0.1         18.0
4                0.631               0.7108              0.1         18.0
5                0.789               0.8887              0.1         18.0
6                0.913               1.0284              0.1         18.0
7                1.200               1.3517              0.1         18.0
8                1.212               1.3652              0.1         18.0
9                1.331               1.4992              0.1         18.0
10               1.484               1.6716              0.1         18.0
11               1.531               1.7245              0.1         18.0
12               1.580               1.7797              0.1         18.0
13               1.717               1.9340              0.1         18.0
14               1.849               2.0827              0.1         18.0
15               2.149               2.4206              0.1         18.0
16               2.310               2.6020              0.1         18.0
17               2.312               2.6042              0.1         18.0
18               3.428               3.8613              0.1         18.0
19               3.552               4.0010              0.1         18.0
20               3.868               4.3569              0.1         18.0
21               4.142               4.6656              0.1         18.0

    DriverPointsNorm
0             0.7955
1             1.0000
2             0.5000
3             0.8636
4             0.7273
5             0.6364
6             0.1818
7             0.0455
8             0.2273
9             0.2727
10            0.4091
11            0.0909
12            0.0000
13            0.1364
14            0.0227
15            0.0000
16            0.0909
17            0.3182
18            0.0000
19            0.0000
20            0.0000
21            0.0000

Saved → japan_quali.csv

## Building rolling features from AUstralia and Chinese GPs

In [ ]:
# Let us build the rolling features from the average of the Australian and ChineseGPs grid positions and final race positions
aus_finish = {
    "RUS": 1,  "ANT": 2,  "LEC": 3,  "HAM": 4,
    "NOR": 5,  "VER": 6,  "BEA": 7,  "LIN": 8,
    "BOR": 9,  "GAS": 10, "OCO": 11, "ALB": 12,
    "LAW": 13, "COL": 14, "SAI": 15, "PER": 16,
    "STR": 17, "ALO": 18, "BOT": 19, "HAD": 20,
    "PIA": 21, "HUL": 22,
}

In [ ]:
# China finish positions (confirmed classification)
# DNF: VER=16, ALO=17, STR=18 | DNS: NOR=19, BOR=20, ALB=21, PIA=22
china_finish = {
    "ANT": 1,  "RUS": 2,  "HAM": 3,  "LEC": 4,
    "BEA": 5,  "GAS": 6,  "LAW": 7,  "HAD": 8,
    "SAI": 9,  "COL": 10, "HUL": 11, "LIN": 12,
    "BOT": 13, "OCO": 14, "PER": 15, "VER": 16,
    "ALO": 17, "STR": 18, "NOR": 19, "BOR": 20,
    "ALB": 21, "PIA": 22,
}

In [ ]:
# Australia grid positions (confirmed qualifying)
# VER P20 (crashed Q1), SAI P21 & STR P22 (power unit issues in quali)
aus_grid = {
    "RUS": 1,  "ANT": 2,  "HAD": 3,  "LEC": 4,  "PIA": 5,
    "NOR": 6,  "HAM": 7,  "LAW": 8,  "LIN": 9,  "BOR": 10,
    "OCO": 11, "HUL": 12, "ALB": 13, "GAS": 14, "COL": 15,
    "BEA": 16, "ALO": 17, "PER": 18, "BOT": 19, "VER": 20,
    "SAI": 21, "STR": 22,
}

In [ ]:
# China grid positions (confirmed qualifying)
# ALB P18 but started from pit lane (parc fermé modification)
china_grid = {
    "ANT": 1,  "RUS": 2,  "HAM": 3,  "LEC": 4,  "PIA": 5,
    "NOR": 6,  "GAS": 7,  "VER": 8,  "HAD": 9,  "BEA": 10,
    "HUL": 11, "COL": 12, "OCO": 13, "LAW": 14, "LIN": 15,
    "BOR": 16, "SAI": 17, "ALB": 18, "ALO": 19, "BOT": 20,
    "STR": 21, "PER": 22,
}

In [ ]:
# CONSTRUCTOR STANDINGS after China (Round 2)
# Source: formula1.com / total-motorsport.com
# ─────────────────────────────────────────────────────────────────────────────
team_points = {
    "Mercedes":     98,
    "Ferrari":      67,
    "McLaren":      18,
    "Haas":         17,
    "Red Bull":     12,
    "Racing Bulls": 12,
    "Alpine":       10,
    "Audi":          2,
    "Williams":      2,
    "Cadillac":      0,
    "Aston Martin":  0,
}

In [ ]:
# DRIVER STANDINGS after China (Round 2)
# Source: autohebdof1.com / total-motorsport.com
# ─────────────────────────────────────────────────────────────────────────────
driver_points = {
    "RUS": 51, "ANT": 47, "LEC": 34, "HAM": 33,
    "BEA": 17, "NOR": 15, "GAS":  9, "VER":  8,
    "LAW":  8, "LIN":  4, "HAD":  4, "PIA":  3,
    "SAI":  2, "BOR":  2, "COL":  1, "OCO":  0,
    "HUL":  0, "ALB":  0, "BOT":  0, "PER":  0,
    "ALO":  0, "STR":  0,
}

In [ ]:
# DRIVER → TEAM MAPPING (2026 season)
# ─────────────────────────────────────────────────────────────────────────────
driver_to_team = {
    "RUS": "Mercedes",    "ANT": "Mercedes",
    "HAM": "Ferrari",     "LEC": "Ferrari",
    "NOR": "McLaren",     "PIA": "McLaren",
    "VER": "Red Bull",    "HAD": "Red Bull",
    "BEA": "Haas",        "OCO": "Haas",
    "LAW": "Racing Bulls","LIN": "Racing Bulls",
    "HUL": "Audi",        "BOR": "Audi",
    "GAS": "Alpine",      "COL": "Alpine",
    "SAI": "Williams",    "ALB": "Williams",
    "PER": "Cadillac",    "BOT": "Cadillac",
    "ALO": "Aston Martin","STR": "Aston Martin",
}

In [ ]:
# BUILD ROLLING FEATURES
# ─────────────────────────────────────────────────────────────────────────────
drivers = list(driver_to_team.keys())
N = len(drivers)  # 22
 
records = []
for drv in drivers:
    aus_fp  = aus_finish[drv]
    chn_fp  = china_finish[drv]
    aus_gp  = aus_grid[drv]
    chn_gp  = china_grid[drv]
 
    # Average finish position (dense rank, so DNFs are ranked last)
    avg_finish_pos = round((aus_fp + chn_fp) / 2, 2)
 
    # Normalised average finish (0 = best, 1 = worst)
    avg_finish_norm = round(((aus_fp - 1) / (N - 1) + (chn_fp - 1) / (N - 1)) / 2, 4)
 
    # Average grid position
    avg_grid_pos = round((aus_gp + chn_gp) / 2, 2)
 
    # Normalised average grid (0 = pole, 1 = last)
    avg_grid_norm = round(((aus_gp - 1) / (N - 1) + (chn_gp - 1) / (N - 1)) / 2, 4)
 
    # DNF rate (1 race out of 2 if DNF/DNS in either)
    dnf_aus = 1 if aus_fp >= 18 else 0   # positions 18-22 = DNF or DNS
    dnf_chn = 1 if chn_fp >= 16 else 0   # VER(16), ALO(17), STR(18) DNF; NOR+ DNS
    dnf_rate = round((dnf_aus + dnf_chn) / 2, 2)
 
    records.append({
        "Driver":          drv,
        "Team":            driver_to_team[drv],
        "AusFinish":       aus_fp,
        "ChinaFinish":     chn_fp,
        "AvgFinishPos":    avg_finish_pos,
        "AvgFinishNorm":   avg_finish_norm,
        "AusGrid":         aus_gp,
        "ChinaGrid_prev":  chn_gp,
        "AvgGridPos":      avg_grid_pos,
        "AvgGridNorm":     avg_grid_norm,
        "DNF_rate":        dnf_rate,
    })
 
rolling_df = pd.DataFrame(records)

In [ ]:
# NORMALISE TEAM & DRIVER STANDINGS
# ─────────────────────────────────────────────────────────────────────────────
max_team_pts   = max(team_points.values())
max_driver_pts = max(driver_points.values())
 
rolling_df["TeamScore"]       = rolling_df["Team"].map(
    {t: max(p, 0.5) / max_team_pts for t, p in team_points.items()}
).round(4)
 
rolling_df["DriverPointsNorm"] = rolling_df["Driver"].map(
    {d: p / max_driver_pts for d, p in driver_points.items()}
).round(4)

In [ ]:
# PRINT SUMMARY TABLE
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 80)
print("  ROLLING FEATURES FOR JAPAN GP PREDICTION")
print("  Based on: Australia (R1) + China (R2)")
print("=" * 80)
print(f"\n{'DRV':<6}{'Team':<16}{'AUS':<5}{'CHN':<5}{'AvgFin':<9}"
      f"{'AvgFinNorm':<12}{'AvgGrid':<9}{'AvgGridNorm':<13}"
      f"{'DNF%':<7}{'TeamScore':<11}{'DrvPtsNorm'}")
print("─" * 100)
for _, r in rolling_df.sort_values("AvgFinishPos").iterrows():
    print(f"{r['Driver']:<6}{r['Team']:<16}{r['AusFinish']:<5}{r['ChinaFinish']:<5}"
          f"{r['AvgFinishPos']:<9}{r['AvgFinishNorm']:<12}{r['AvgGridPos']:<9}"
          f"{r['AvgGridNorm']:<13}{r['DNF_rate']:<7}{r['TeamScore']:<11}"
          f"{r['DriverPointsNorm']}")
 
rolling_df.to_csv("rolling_features_aus_china.csv", index=False)
print("\nSaved → rolling_features_aus_china.csv")

================================================================================
  ROLLING FEATURES FOR JAPAN GP PREDICTION
  Based on: Australia (R1) + China (R2)
================================================================================

DRV   Team            AUS  CHN  AvgFin   AvgFinNorm  AvgGrid  AvgGridNorm  DNF%   TeamScore  DrvPtsNorm
────────────────────────────────────────────────────────────────────────────────────────────────────
RUS   Mercedes        1    2    1.5      0.0238      1.5      0.0238       0.0    1.0        1.0
ANT   Mercedes        2    1    1.5      0.0238      1.5      0.0238       0.0    1.0        0.9216
HAM   Ferrari         4    3    3.5      0.119       5.0      0.1905       0.0    0.6837     0.6471
LEC   Ferrari         3    4    3.5      0.119       4.0      0.1429       0.0    0.6837     0.6667
BEA   Haas            7    5    6.0      0.2381      13.0     0.5714       0.0    0.1735     0.3333
GAS   Alpine          10   6    8.0      0.3333      10.5     0.4524       0.0    0.102      0.1765
LAW   Racing Bulls    13   7    10.0     0.4286      11.0     0.4762       0.0    0.1224     0.1569
LIN   Racing Bulls    8    12   10.0     0.4286      12.0     0.5238       0.0    0.1224     0.0784
VER   Red Bull        6    16   11.0     0.4762      14.0     0.619        0.5    0.1224     0.1569
COL   Alpine          14   10   12.0     0.5238      13.5     0.5952       0.0    0.102      0.0196
NOR   McLaren         5    19   12.0     0.5238      6.0      0.2381       0.5    0.1837     0.2941
SAI   Williams        15   9    12.0     0.5238      19.0     0.8571       0.0    0.0204     0.0392
OCO   Haas            11   14   12.5     0.5476      12.0     0.5238       0.0    0.1735     0.0
HAD   Red Bull        20   8    14.0     0.619       6.0      0.2381       0.5    0.1224     0.0784
BOR   Audi            9    20   14.5     0.6429      13.0     0.5714       0.5    0.0204     0.0392
PER   Cadillac        16   15   15.5     0.6905      20.0     0.9048       0.0    0.0051     0.0
BOT   Cadillac        19   13   16.0     0.7143      19.5     0.881        0.5    0.0051     0.0
HUL   Audi            22   11   16.5     0.7381      11.5     0.5          0.5    0.0204     0.0
ALB   Williams        12   21   16.5     0.7381      15.5     0.6905       0.5    0.0204     0.0
ALO   Aston Martin    18   17   17.5     0.7857      18.0     0.8095       1.0    0.0051     0.0
STR   Aston Martin    17   18   17.5     0.7857      21.5     0.9762       0.5    0.0051     0.0
PIA   McLaren         21   22   21.5     0.9762      5.0      0.1905       1.0    0.1837     0.0588

Saved → rolling_features_aus_china.csv

In [ ]:
# HOW TO MERGE INTO YOUR MAIN DATAFRAME
# ─────────────────────────────────────────────────────────────────────────────
# After building your Japan quali df, merge like this:
#
df = quali_df.merge(
    rolling_df[["Driver", "AvgFinishNorm", "AvgGridNorm",
                "DNF_rate", "TeamScore", "Team"]],
    on="Driver", how="left"
   )

In [ ]:
df.head()

,Driver,S1,S2,S3,BestLap_s,UltimateLap_s,JapanGapFromPole_s,JapanGapFromPolePct,JapanGrid,RainProbability,Temperature,DriverPoints,DriverPointsNorm,AvgFinishNorm,AvgGridNorm,DNF_rate,TeamScore,Team
0,ANT,31.827,39.398,17.464,88.778,88.689,0.000,0.0000,1,0.1,18.0,35,0.7955,0.0238,0.0238,0.0,1.0000,Mercedes
1,RUS,31.782,39.607,17.616,89.076,89.005,0.298,0.3357,2,0.1,18.0,44,1.0000,0.0238,0.0238,0.0,1.0000,Mercedes
2,PIA,31.954,39.557,17.577,89.132,89.088,0.354,0.3987,3,0.1,18.0,22,0.5000,0.9762,0.1905,1.0,0.1837,McLaren
3,LEC,31.655,39.855,17.668,89.303,89.178,0.525,0.5914,4,0.1,18.0,38,0.8636,0.1190,0.1429,0.0,0.6837,Ferrari
4,NOR,32.049,39.716,17.627,89.409,89.392,0.631,0.7108,5,0.1,18.0,32,0.7273,0.5238,0.2381,0.5,0.1837,McLaren

 ## Analysing FP2 pace for Japan

In [ ]:
# ── Load FP2 ──────────────────────────────────────────────────────────────────
session = fastf1.get_session(2026, "Japan", "FP2")
session.load(telemetry=False, weather=False, messages=False)

laps = session.laps.copy()

# ── Helper: convert timedelta to seconds ─────────────────────────────────────
def td_to_s(td):
    if pd.isnull(td):
        return np.nan
    return td.total_seconds()

laps["LapTime_s"] = laps["LapTime"].apply(td_to_s)

# ── Filter criteria ───────────────────────────────────────────────────────────
# Keep only representative race-sim laps:
#   - Not an in/out lap (IsAccurate flag or LapNumber > 1 in stint)
#   - Lap time within 110% of session median (removes outliers, VSC laps)
#   - Compound is MEDIUM or HARD (race compounds — not quali soft runs)
#   - Stint lap number >= 3 (skip initial warm-up laps)

laps = laps[laps["IsAccurate"] == True].copy()  # FastF1 flags dodgy laps

COMPOUNDS = ["MEDIUM", "HARD"]
laps = laps[laps["Compound"].isin(COMPOUNDS)]

# Stint lap number — laps within a stint counted from 1
laps["StintLapNum"] = laps.groupby(["Driver", "Stint"]).cumcount() + 1
laps = laps[laps["StintLapNum"] >= 3]

# Remove outliers: keep within 107% of driver's own median
def within_107(group):
    med = group["LapTime_s"].median()
    return group[group["LapTime_s"] <= med * 1.07]

laps = laps.groupby("Driver", group_keys=False).apply(within_107)

# ── Aggregate per driver ──────────────────────────────────────────────────────
records = []
for driver, grp in laps.groupby("Driver"):
    med_pace   = grp["LapTime_s"].median()
    mean_pace  = grp["LapTime_s"].mean()
    best_pace  = grp["LapTime_s"].min()
    lap_count  = len(grp)

    # Compound breakdown (useful for context)
    compound_counts = grp["Compound"].value_counts().to_dict()

    records.append({
        "Driver":           driver,
        "FP2_MedianPace_s": round(med_pace, 3),
        "FP2_MeanPace_s":   round(mean_pace, 3),
        "FP2_BestPace_s":   round(best_pace, 3),
        "FP2_LapCount":     lap_count,
        "FP2_Compounds":    str(compound_counts),
    })

fp2_df = pd.DataFrame(records).sort_values("FP2_MedianPace_s").reset_index(drop=True)

# ── Gap from fastest driver in FP2 ───────────────────────────────────────────
ref_pace = fp2_df["FP2_MedianPace_s"].min()
fp2_df["FP2_GapToFastest_s"] = (fp2_df["FP2_MedianPace_s"] - ref_pace).round(3)

print(fp2_df[["Driver", "FP2_MedianPace_s", "FP2_GapToFastest_s",
              "FP2_LapCount", "FP2_Compounds"]])

fp2_df.to_csv("japan_fp2_pace.csv", index=False)
print("\nSaved → japan_fp2_pace.csv")

core           INFO 	Loading data for Japanese Grand Prix - Practice 2 [v3.8.2]
INFO:fastf1.fastf1.core:Loading data for Japanese Grand Prix - Practice 2 [v3.8.2]
req            INFO 	No cached data found for session_info. Loading data...
INFO:fastf1.fastf1.req:No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
INFO:fastf1.api:Fetching session info data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
INFO:fastf1.fastf1.req:No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
INFO:fastf1.api:Fetching driver list...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
INFO:fastf1.api:Fetching session status data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
INFO:fastf1.api:Fetching track status data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
INFO:fastf1.api:Fetching timing data...
_api           INFO 	Parsing timing data...
INFO:fastf1.api:Parsing timing data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
INFO:fastf1.api:Fetching timing app data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
core           INFO 	Processing timing data...
INFO:fastf1.fastf1.core:Processing timing data...
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']
INFO:fastf1.fastf1.core:Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']

   Driver  FP2_MedianPace_s  FP2_GapToFastest_s  FP2_LapCount   FP2_Compounds
0     ANT            94.496               0.000             7   {'MEDIUM': 7}
1     STR            95.042               0.546             2   {'MEDIUM': 2}
2     RUS            95.079               0.583             6   {'MEDIUM': 6}
3     LEC            95.243               0.747             8   {'MEDIUM': 8}
4     PIA            95.808               1.312             8   {'MEDIUM': 8}
5     GAS            95.919               1.423            10    {'HARD': 10}
6     OCO            95.958               1.462            12  {'MEDIUM': 12}
7     HUL            96.146               1.650             6     {'HARD': 6}
8     HAD            96.161               1.665             9     {'HARD': 9}
9     BEA            96.170               1.674            10  {'MEDIUM': 10}
10    VER            96.299               1.803            12    {'HARD': 12}
11    HAM            96.424               1.928             3   {'MEDIUM': 3}
12    LAW            96.774               2.278             8   {'MEDIUM': 8}
13    COL            96.826               2.330            10  {'MEDIUM': 10}
14    ALB            97.219               2.723            10  {'MEDIUM': 10}
15    SAI            97.222               2.726            10    {'HARD': 10}
16    BOT            98.054               3.558            11  {'MEDIUM': 11}
17    PER            98.173               3.677             3     {'HARD': 3}
18    NOR           112.215              17.719             2   {'MEDIUM': 2}

Saved → japan_fp2_pace.csv

/tmp/ipykernel_9900/275636439.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  laps["StintLapNum"] = laps.groupby(["Driver", "Stint"]).cumcount() + 1
/tmp/ipykernel_9900/275636439.py:36: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  laps = laps.groupby("Driver", group_keys=False).apply(within_107)

In [ ]:
df_final = df.merge(
    fp2_df[["Driver", "FP2_GapToFastest_s"]],
    on="Driver", how="left"
   )

In [ ]:
df_final.head()

,Driver,S1,S2,S3,BestLap_s,UltimateLap_s,JapanGapFromPole_s,JapanGapFromPolePct,JapanGrid,RainProbability,Temperature,DriverPoints,DriverPointsNorm,AvgFinishNorm,AvgGridNorm,DNF_rate,TeamScore,Team,FP2_GapToFastest_s
0,ANT,31.827,39.398,17.464,88.778,88.689,0.000,0.0000,1,0.1,18.0,35,0.7955,0.0238,0.0238,0.0,1.0000,Mercedes,0.000
1,RUS,31.782,39.607,17.616,89.076,89.005,0.298,0.3357,2,0.1,18.0,44,1.0000,0.0238,0.0238,0.0,1.0000,Mercedes,0.583
2,PIA,31.954,39.557,17.577,89.132,89.088,0.354,0.3987,3,0.1,18.0,22,0.5000,0.9762,0.1905,1.0,0.1837,McLaren,1.312
3,LEC,31.655,39.855,17.668,89.303,89.178,0.525,0.5914,4,0.1,18.0,38,0.8636,0.1190,0.1429,0.0,0.6837,Ferrari,0.747
4,NOR,32.049,39.716,17.627,89.409,89.392,0.631,0.7108,5,0.1,18.0,32,0.7273,0.5238,0.2381,0.5,0.1837,McLaren,17.719

## Feature Engineering

In [ ]:
feature_cols = [
"UltimateLap_s",        # Japan quali: best S1+S2+S3
"JapanGapFromPole_s",   # Japan quali: gap to pole
"JapanGrid",            # Japan qualifying position
"FP2_GapToFastest_s",   # FP2 long-run race pace
"TeamScore",            # Constructor points normalised (after China)
"DriverPointsNorm",     # Driver points normalised (after China)
"AvgFinishNorm",        # Rolling avg finish (Aus + China)
"AvgGridNorm",          # Rolling avg grid (Aus + China)
"DNF_rate",             # Reliability signal
"RainProbability",      # Weather (manual)
"Temperature",          # Weather (manual)
]

In [ ]:
# Lets build our target variable
# ── Target: rolling normalised race score from Aus + China ───────────────
n_drivers = len(df_final)

# Normalise average finish position (0 = best, 1 = worst)
avg_finish_norm = df_final["AvgFinishNorm"]  # already in your df

# Normalise average grid position (0 = best, 1 = worst)  
avg_grid_norm = df_final["AvgGridNorm"]      # already in your df

# Composite target — weight finish more than grid (60/40)
df_final["RaceScore"] = (
    0.6 * avg_finish_norm +
    0.4 * avg_grid_norm
).round(4)

X = df_final[feature_cols].copy()
y = df_final["RaceScore"]

In [ ]:
import sklearn
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import mean_absolute_error
from xgboost import XGBRegressor

In [ ]:
# Filling any missing values with median
from sklearn.impute import SimpleImputer
imputer   = SimpleImputer(strategy="median")
X_imputed = imputer.fit_transform(X)

### Modelling

In [ ]:
from sklearn.linear_model import Ridge, ElasticNet
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import numpy as np

# ── Compare multiple models with LOO-CV ──────────────────────────────────────
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import mean_absolute_error

In [ ]:
models = {
    "Ridge":        Ridge(alpha=1.0),
    "ElasticNet":   ElasticNet(alpha=0.1, l1_ratio=0.5),
    "RandomForest": RandomForestRegressor(
                        n_estimators=100, max_depth=3,
                        min_samples_leaf=3, random_state=42),
    "GradientBoost": GradientBoostingRegressor(
                        n_estimators=100, learning_rate=0.05,
                        max_depth=2, subsample=0.8, random_state=42),
    "XGBoost":      XGBRegressor(
                        n_estimators=100, learning_rate=0.05,
                        max_depth=2, subsample=0.8,
                        colsample_bytree=0.8, reg_lambda=2.0,
                        random_state=42),
}

loo = LeaveOneOut()
results = {}

for name, mdl in models.items():
    # Ridge and ElasticNet benefit from scaling
    if name in ["Ridge", "ElasticNet"]:
        pipe = Pipeline([("scaler", StandardScaler()), ("model", mdl)])
    else:
        pipe = Pipeline([("model", mdl)])

    errors = []
    for train_idx, test_idx in loo.split(X_imputed):
        X_tr, X_te = X_imputed[train_idx], X_imputed[test_idx]
        y_tr, y_te = y.iloc[train_idx],    y.iloc[test_idx]
        pipe.fit(X_tr, y_tr)
        errors.append(abs(pipe.predict(X_te)[0] - y_te.iloc[0]))

    results[name] = {
        "MAE":    round(np.mean(errors), 4),
        "StdDev": round(np.std(errors), 4),
    }

In [ ]:
# ── Print comparison ──────────────────────────────────────────────────────────
print(f"\n{'Model':<18} {'LOO MAE':>8} {'Std Dev':>8}  {'Verdict'}")
print("─" * 55)
for name, res in sorted(results.items(), key=lambda x: x[1]["MAE"]):
    best = " ← best" if res["MAE"] == min(r["MAE"] for r in results.values()) else ""
    print(f"{name:<18} {res['MAE']:>8.4f} {res['StdDev']:>8.4f}  {best}")

Model               LOO MAE  Std Dev  Verdict
───────────────────────────────────────────────────────
Ridge                0.0245   0.0257   ← best
GradientBoost        0.0524   0.0615
ElasticNet           0.0584   0.0374
XGBoost              0.0687   0.0740
RandomForest         0.0806   0.0710

In [ ]:
# ── Use the best model for final prediction ───────────────────────────────────
best_name = min(results, key=lambda x: results[x]["MAE"])
print(f"\nUsing: {best_name}")

best_model = models[best_name]
if best_name in ["Ridge", "ElasticNet"]:
    final_pipe = Pipeline([("scaler", StandardScaler()), ("model", best_model)])
else:
    final_pipe = Pipeline([("model", best_model)])

final_pipe.fit(X_imputed, y)
df["PredictedScore"] = final_pipe.predict(X_imputed)

Using: Ridge

In [ ]:
final_pipe.fit(X_imputed, y)
df["PredictedScore"] = final_pipe.predict(X_imputed)

# ── Predicted finishing order ─────────────────────────────────────────────────
final = df.sort_values("PredictedScore").reset_index(drop=True)

print("\n" + "=" * 68)
print("   PREDICTED FINISHING ORDER — 2026 JAPANESE GRAND PRIX")
print("   Target: Aus + China avg finish + avg grid (rolling)")
print("=" * 68)
print(f"  {'P':<4}{'DRV':<6}{'Team':<22}{'Score'}")
print("  " + "─" * 40)
for i, row in final.iterrows():
    print(f"  {i+1:<4}{row['Driver']:<6}{row['Team']:<22}{row['PredictedScore']:.4f}")

podium = final.head(3)
print(f"\n  {'='*45}")
print(f"  🥇 P1: {podium.iloc[0]['Driver']} ({podium.iloc[0]['Team']})")
print(f"  🥈 P2: {podium.iloc[1]['Driver']} ({podium.iloc[1]['Team']})")
print(f"  🥉 P3: {podium.iloc[2]['Driver']} ({podium.iloc[2]['Team']})")
print(f"\n  Best model:        {best_name}")
print(f"  LOO MAE:           {results[best_name]['MAE']:.4f}")
print(f"  LOO Std Dev:       {results[best_name]['StdDev']:.4f}")
print(f"  Weather:           {df['Temperature'].iloc[0]:.1f}°C | Rain: {df['RainProbability'].iloc[0]:.0%}")
print(f"  {'='*45}")

# ── Feature importances (tree models only) ────────────────────────────────────
if best_name in ["RandomForest", "GradientBoost", "XGBoost"]:
    importances = final_pipe.named_steps["model"].feature_importances_
    print("\nFeature importances:")
    for feat, imp in sorted(zip(feature_cols, importances), key=lambda x: -x[1]):
        bar = "█" * int(imp * 50)
        print(f"  {feat:<28} {imp:.4f}  {bar}")
elif best_name in ["Ridge", "ElasticNet"]:
    coefficients = final_pipe.named_steps["model"].coef_
    print("\nFeature coefficients (higher = more influence):")
    for feat, coef in sorted(zip(feature_cols, coefficients), key=lambda x: -abs(x[1])):
        bar = "█" * int(abs(coef) * 20)
        print(f"  {feat:<28} {coef:+.4f}  {bar}")

====================================================================
   PREDICTED FINISHING ORDER — 2026 JAPANESE GRAND PRIX
   Target: Aus + China avg finish + avg grid (rolling)
====================================================================
  P   DRV   Team                  Score
  ────────────────────────────────────────
  1   RUS   Mercedes              0.0203
  2   ANT   Mercedes              0.0216
  3   LEC   Ferrari               0.1321
  4   HAM   Ferrari               0.1572
  5   GAS   Alpine                0.3976
  6   BEA   Haas                  0.4036
  7   NOR   McLaren               0.4130
  8   LAW   Racing Bulls          0.4638
  9   LIN   Racing Bulls          0.4646
  10  HAD   Red Bull              0.4983
  11  OCO   Haas                  0.5250
  12  VER   Red Bull              0.5311
  13  COL   Alpine                0.5479
  14  BOR   Audi                  0.6049
  15  PIA   McLaren               0.6339
  16  SAI   Williams              0.6345
  17  HUL   Audi                  0.6427
  18  ALB   Williams              0.7086
  19  PER   Cadillac              0.7512
  20  BOT   Cadillac              0.7784
  21  ALO   Aston Martin          0.8194
  22  STR   Aston Martin          0.8499

  =============================================
  🥇 P1: RUS (Mercedes)
  🥈 P2: ANT (Mercedes)
  🥉 P3: LEC (Ferrari)

  Best model:        Ridge
  LOO MAE:           0.0245
  LOO Std Dev:       0.0257
  Weather:           18.0°C | Rain: 10%
  =============================================

Feature coefficients (higher = more influence):
  AvgFinishNorm                +0.1194  ██
  AvgGridNorm                  +0.0783  █
  TeamScore                    -0.0253
  DNF_rate                     +0.0138
  JapanGapFromPole_s           +0.0113
  DriverPointsNorm             -0.0111
  UltimateLap_s                +0.0111
  FP2_GapToFastest_s           -0.0005
  JapanGrid                    +0.0004
  RainProbability              +0.0000
  Temperature                  +0.0000

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# ── Get predictions from all models ──────────────────────────────────────────
all_predictions = {}

for name, mdl in models.items():
    if name in ["Ridge", "ElasticNet"]:
        pipe = Pipeline([("scaler", StandardScaler()), ("model", mdl)])
    else:
        pipe = Pipeline([("model", mdl)])

    pipe.fit(X_imputed, y)
    preds = pipe.predict(X_imputed)
    ranked = pd.Series(preds, index=df["Driver"]).rank(method="min").astype(int)
    all_predictions[name] = ranked

pred_df = pd.DataFrame(all_predictions)
pred_df["BestModelPos"] = pd.Series(
    final_pipe.predict(X_imputed), index=df["Driver"]
).rank(method="min").astype(int)

pred_df = pred_df.sort_values("BestModelPos")

# ── Print all model predictions side by side ──────────────────────────────────
print("\n" + "=" * 85)
print("   PREDICTED FINISHING ORDER — 2026 JAPANESE GRAND PRIX")
print("   All models compared")
print("=" * 85)

col_w = 14
header = f"  {'DRV':<6}{'Team':<20}"
for name in models.keys():
    header += f"{name:>{col_w}}"
header += f"  {'★ Best':>{col_w}}"
print(header)
print("  " + "─" * 78)

for driver in pred_df.index:
    team = df.loc[df["Driver"] == driver, "Team"].values[0]
    row  = f"  {driver:<6}{team:<20}"
    for name in models.keys():
        pos = pred_df.loc[driver, name]
        row += f"  P{pos:<{col_w-2}}"
    best_pos = pred_df.loc[driver, "BestModelPos"]
    row += f"  P{best_pos:<{col_w-2}}"
    print(row)

# ── Podium from best model ────────────────────────────────────────────────────
best_order = pred_df.sort_values("BestModelPos")
p1 = best_order.index[0]
p2 = best_order.index[1]
p3 = best_order.index[2]

t1 = df.loc[df["Driver"] == p1, "Team"].values[0]
t2 = df.loc[df["Driver"] == p2, "Team"].values[0]
t3 = df.loc[df["Driver"] == p3, "Team"].values[0]

print(f"\n  {'='*55}")
print(f"  Best model: {best_name} (LOO MAE: {results[best_name]['MAE']:.4f})")
print(f"  🥇 P1: {p1} ({t1})")
print(f"  🥈 P2: {p2} ({t2})")
print(f"  🥉 P3: {p3} ({t3})")
print(f"  Weather: {df['Temperature'].iloc[0]:.1f}°C | Rain: {df['RainProbability'].iloc[0]:.0%}")
print(f"  {'='*55}")

# ── Consensus podium ──────────────────────────────────────────────────────────
print("\n  CONSENSUS PODIUM (across all models):")
print("  " + "─" * 35)
medals = ["🥇", "🥈", "🥉"]
for pos in [1, 2, 3]:
    pos_counts = {}
    for name in models.keys():
        drivers_at_pos = pred_df[pred_df[name] == pos].index.tolist()
        for d in drivers_at_pos:
            pos_counts[d] = pos_counts.get(d, 0) + 1
    if pos_counts:
        top   = max(pos_counts, key=pos_counts.get)
        votes = pos_counts[top]
        print(f"  {medals[pos-1]} P{pos}: {top} — {votes}/{len(models)} models agree")
print(f"  {'='*55}")

=====================================================================================
   PREDICTED FINISHING ORDER — 2026 JAPANESE GRAND PRIX
   All models compared
=====================================================================================
  DRV   Team                         Ridge    ElasticNet  RandomForest GradientBoost       XGBoost          ★ Best
  ──────────────────────────────────────────────────────────────────────────────
  RUS   Mercedes              P1             P2             P1             P2             P1             P1
  ANT   Mercedes              P2             P1             P1             P1             P1             P2
  LEC   Ferrari               P3             P3             P1             P3             P3             P3
  HAM   Ferrari               P4             P4             P4             P4             P4             P4
  GAS   Alpine                P5             P6             P5             P5             P5             P5
  BEA   Haas                  P6             P5             P6             P6             P6             P6
  NOR   McLaren               P7             P7             P7             P7             P7             P7
  LAW   Racing Bulls          P8             P8             P8             P8             P8             P8
  LIN   Racing Bulls          P9             P9             P9             P9             P9             P9
  HAD   Red Bull              P10            P10            P10            P10            P10            P10
  OCO   Haas                  P11            P12            P12            P11            P11            P11
  VER   Red Bull              P12            P11            P11            P12            P12            P12
  COL   Alpine                P13            P13            P13            P13            P13            P13
  BOR   Audi                  P14            P14            P16            P14            P15            P14
  PIA   McLaren               P15            P17            P14            P17            P14            P15
  SAI   Williams              P16            P15            P15            P15            P16            P16
  HUL   Audi                  P17            P16            P17            P16            P17            P17
  ALB   Williams              P18            P18            P18            P18            P18            P18
  PER   Cadillac              P19            P19            P20            P19            P20            P19
  BOT   Cadillac              P20            P20            P22            P19            P19            P20
  ALO   Aston Martin          P21            P21            P21            P21            P21            P21
  STR   Aston Martin          P22            P22            P19            P22            P22            P22

  =======================================================
  Best model: Ridge (LOO MAE: 0.0245)
  🥇 P1: RUS (Mercedes)
  🥈 P2: ANT (Mercedes)
  🥉 P3: LEC (Ferrari)
  Weather: 18.0°C | Rain: 10%
  =======================================================

  CONSENSUS PODIUM (across all models):
  ───────────────────────────────────
  🥇 P1: ANT — 4/5 models agree
  🥈 P2: RUS — 2/5 models agree
  🥉 P3: LEC — 4/5 models agree
  =======================================================

Pulling requests from Fast f1

In [4]:
import sys
print(sys.executable)

/usr/bin/python3

In [5]:
#import sys
!{sys.executable} -m pip install fastf1

Collecting fastf1
  Downloading fastf1-3.8.3-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: cryptography in /usr/local/lib/python3.12/dist-packages (from fastf1) (43.0.3)
Requirement already satisfied: matplotlib<4.0.0,>=3.8.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (3.10.0)
Requirement already satisfied: numpy<3.0.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.0.2)
Requirement already satisfied: pandas<3.0.0,>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.2.2)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from fastf1) (4.9.6)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.12.3)
Requirement already satisfied: pyjwt in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.12.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.9.0.post0)
Collecting rapidfuzz (from fastf1)
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Collecting requests-cache>=1.0.0 (from fastf1)
  Downloading requests_cache-1.3.1-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: requests>=2.30.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.32.4)
Requirement already satisfied: scipy<2.0.0,>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (1.16.3)
Collecting signalrcore (from fastf1)
  Downloading signalrcore-1.0.2-py3-none-any.whl.metadata (13 kB)
Collecting timple>=0.1.6 (from fastf1)
  Downloading timple-0.1.8-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: websockets>=10.3 in /usr/local/lib/python3.12/dist-packages (from fastf1) (15.0.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.1.1->fastf1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.1.1->fastf1) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->fastf1) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (2026.4.22)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache>=1.0.0->fastf1) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache>=1.0.0->fastf1)
  Downloading cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Collecting url-normalize>=2.0 (from requests-cache>=1.0.0->fastf1)
  Downloading url_normalize-3.0.0-py3-none-any.whl.metadata (7.5 kB)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography->fastf1) (2.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (0.4.2)
Requirement already satisfied: msgpack==1.1.2 in /usr/local/lib/python3.12/dist-packages (from signalrcore->fastf1) (1.1.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography->fastf1) (3.0)
Downloading fastf1-3.8.3-py3-none-any.whl (135 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 136.0/136.0 kB 8.4 MB/s eta 0:00:00
Downloading requests_cache-1.3.1-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.2/70.2 kB 5.2 MB/s eta 0:00:00
Downloading timple-0.1.8-py3-none-any.whl (17 kB)
Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 87.2 MB/s eta 0:00:00:00:01
Downloading signalrcore-1.0.2-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.6/55.6 kB 3.9 MB/s eta 0:00:00
Downloading cattrs-26.1.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 4.8 MB/s eta 0:00:00
Downloading url_normalize-3.0.0-py3-none-any.whl (16 kB)
Installing collected packages: url-normalize, signalrcore, rapidfuzz, cattrs, requests-cache, timple, fastf1
Successfully installed cattrs-26.1.0 fastf1-3.8.3 rapidfuzz-3.14.5 requests-cache-1.3.1 signalrcore-1.0.2 timple-0.1.8 url-normalize-3.0.0

In [7]:
import fastf1

In [8]:
# ── Load Miami qualifying session ─────────────────────────────────────────────
session = fastf1.get_session(2026, "Miami", "Q")
session.load(telemetry=False, weather=True, messages=False)
 
laps = session.laps
 
def td_to_s(td):
    if pd.isnull(td):
        return np.nan
    return td.total_seconds()
 
records = []
for driver in laps["Driver"].unique():
    drv_all = laps.pick_drivers(driver).pick_wo_box()
    if drv_all.empty:
        continue
    best_s1  = drv_all["Sector1Time"].dropna().min()
    best_s2  = drv_all["Sector2Time"].dropna().min()
    best_s3  = drv_all["Sector3Time"].dropna().min()
    best_lap = drv_all["LapTime"].dropna().min()
    records.append({
        "Driver":    driver,
        "S1":        td_to_s(best_s1),
        "S2":        td_to_s(best_s2),
        "S3":        td_to_s(best_s3),
        "BestLap_s": td_to_s(best_lap),
    })
 
quali_df = pd.DataFrame(records)
quali_df["UltimateLap_s"] = (quali_df["S1"] + quali_df["S2"] + quali_df["S3"]).round(3)
 
pole_time = quali_df["BestLap_s"].min()
quali_df["MiamiGapFromPole_s"]   = (quali_df["BestLap_s"] - pole_time).round(3)
quali_df["MiamiGapFromPolePct"]  = (quali_df["MiamiGapFromPole_s"] / pole_time * 100).round(4)
 
quali_df = quali_df.sort_values("BestLap_s").reset_index(drop=True)
quali_df["MiamiGrid"] = quali_df.index + 1

req         WARNING 	DEFAULT CACHE ENABLED! (24.0 KB) /root/.cache/fastf1
WARNING:fastf1.fastf1.req:DEFAULT CACHE ENABLED! (24.0 KB) /root/.cache/fastf1
core           INFO 	Loading data for Miami Grand Prix - Qualifying [v3.8.3]
INFO:fastf1.fastf1.core:Loading data for Miami Grand Prix - Qualifying [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
INFO:fastf1.fastf1.req:No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
INFO:fastf1.api:Fetching session info data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
INFO:fastf1.fastf1.req:No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
INFO:fastf1.api:Fetching driver list...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
INFO:fastf1.api:Fetching session status data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
INFO:fastf1.api:Fetching track status data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
INFO:fastf1.api:Fetching timing data...
_api           INFO 	Parsing timing data...
INFO:fastf1.api:Parsing timing data...
_api        WARNING 	Driver 81: Encountered 1 timing integrity error(s) near lap(s): [3].
This might be a bug and should be reported.
WARNING:fastf1.api:Driver 81: Encountered 1 timing integrity error(s) near lap(s): [3].
This might be a bug and should be reported.
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
INFO:fastf1.api:Fetching timing app data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
core           INFO 	Processing timing data...
INFO:fastf1.fastf1.core:Processing timing data...
req            INFO 	No cached data found for weather_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
INFO:fastf1.api:Fetching weather data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['12', '3', '16', '1', '63', '44', '81', '43', '10', '6', '27', '30', '87', '55', '31', '23', '41', '14', '18', '77', '11', '5']
INFO:fastf1.fastf1.core:Finished loading data for 22 drivers: ['12', '3', '16', '1', '63', '44', '81', '43', '10', '6', '27', '30', '87', '55', '31', '23', '41', '14', '18', '77', '11', '5']

In [13]:
quali_df.head(10)

,Driver,S1,S2,S3,BestLap_s,UltimateLap_s,MiamiGapFromPole_s,MiamiGapFromPolePct,MiamiGrid,RainProbability,Temperature,DriverPoints,DriverPointsNorm
0,ANT,29.743,33.431,24.624,87.798,87.798,0.000,0.0000,1,0.4,28.0,72,1.0000
1,VER,30.072,33.172,24.646,87.964,87.890,0.166,0.1891,2,0.4,28.0,12,0.1667
2,LEC,29.861,33.339,24.744,88.143,87.944,0.345,0.3929,3,0.4,28.0,49,0.6806
3,NOR,30.053,33.258,24.814,88.183,88.125,0.385,0.4385,4,0.4,28.0,25,0.3472
4,RUS,29.806,33.500,24.661,88.197,87.967,0.399,0.4545,5,0.4,28.0,63,0.8750
5,HAM,29.907,33.402,24.743,88.319,88.052,0.521,0.5934,6,0.4,28.0,41,0.5694
6,PIA,29.945,33.248,24.877,88.332,88.070,0.534,0.6082,7,0.4,28.0,21,0.2917
7,COL,30.247,33.624,24.829,88.762,88.700,0.964,1.0980,8,0.4,28.0,1,0.0139
8,HAD,30.272,33.398,24.849,88.789,88.519,0.991,1.1287,9,0.4,28.0,4,0.0556
9,GAS,30.194,33.640,24.804,88.810,88.638,1.012,1.1526,10,0.4,28.0,15,0.2083

Adding weather conditions

In [10]:
rain_probability = 0.40   # 40% precipitation probability (race day)
temperature      = 28.0   # ~28°C peak, ~25°C at earlier 13:00 start

quali_df["RainProbability"] = rain_probability
quali_df["Temperature"]     = temperature

In [11]:
# ── Driver standings after Japan GP (R3) ─────────────────────────────────────
driver_points = {
    "ANT": 72, "RUS": 63, "LEC": 49, "HAM": 41,
    "NOR": 25, "PIA": 21, "BEA": 17, "GAS": 15,
    "VER": 12, "LAW": 10, "LIN":  4, "HAD":  4,
    "BOR":  2, "SAI":  2, "COL":  1, "OCO":  1,
    "ALB":  0, "PER":  0, "STR":  0, "ALO":  0,
    "BOT":  0, "HUL":  0,
}

max_driver_pts = max(v for v in driver_points.values() if v > 0)
quali_df["DriverPoints"]     = quali_df["Driver"].map(driver_points).fillna(0)
quali_df["DriverPointsNorm"] = (quali_df["DriverPoints"] / max_driver_pts).round(4)

In [12]:
print(quali_df[["Driver", "S1", "S2", "S3", "UltimateLap_s",
                "BestLap_s", "MiamiGrid", "MiamiGapFromPole_s",
                "MiamiGapFromPolePct", "RainProbability", "Temperature",
                "DriverPointsNorm"]])

   Driver      S1      S2      S3  UltimateLap_s  BestLap_s  MiamiGrid  \
0     ANT  29.743  33.431  24.624         87.798     87.798          1
1     VER  30.072  33.172  24.646         87.890     87.964          2
2     LEC  29.861  33.339  24.744         87.944     88.143          3
3     NOR  30.053  33.258  24.814         88.125     88.183          4
4     RUS  29.806  33.500  24.661         87.967     88.197          5
5     HAM  29.907  33.402  24.743         88.052     88.319          6
6     PIA  29.945  33.248  24.877         88.070     88.332          7
7     COL  30.247  33.624  24.829         88.700     88.762          8
8     HAD  30.272  33.398  24.849         88.519     88.789          9
9     GAS  30.194  33.640  24.804         88.638     88.810         10
10    BEA  30.728  33.723  24.843         89.294     89.340         11
11    HUL  30.216  33.875  25.134         89.225     89.439         12
12    LAW  30.530  33.810  24.998         89.338     89.499         13
13    SAI  30.677  33.763  24.984         89.424     89.540         14
14    ALB  30.595  33.748  25.111         89.454     89.720         15
15    OCO  30.786  33.795  25.055         89.636     89.772         16
16    LIN  30.913  34.176  24.951         90.040     90.133         17
17    ALO  31.073  34.339  25.686         91.098     91.098         18
18    STR  31.125  34.539  25.423         91.087     91.164         19
19    BOT  31.243  34.756  25.630         91.629     91.629         20
20    PER  31.197  34.530  25.292         91.019     91.967         21
21    BOR  31.944  34.988  26.805         93.737     93.737         22

    MiamiGapFromPole_s  MiamiGapFromPolePct  RainProbability  Temperature  \
0                0.000               0.0000              0.4         28.0
1                0.166               0.1891              0.4         28.0
2                0.345               0.3929              0.4         28.0
3                0.385               0.4385              0.4         28.0
4                0.399               0.4545              0.4         28.0
5                0.521               0.5934              0.4         28.0
6                0.534               0.6082              0.4         28.0
7                0.964               1.0980              0.4         28.0
8                0.991               1.1287              0.4         28.0
9                1.012               1.1526              0.4         28.0
10               1.542               1.7563              0.4         28.0
11               1.641               1.8691              0.4         28.0
12               1.701               1.9374              0.4         28.0
13               1.742               1.9841              0.4         28.0
14               1.922               2.1891              0.4         28.0
15               1.974               2.2483              0.4         28.0
16               2.335               2.6595              0.4         28.0
17               3.300               3.7586              0.4         28.0
18               3.366               3.8338              0.4         28.0
19               3.831               4.3634              0.4         28.0
20               4.169               4.7484              0.4         28.0
21               5.939               6.7644              0.4         28.0

    DriverPointsNorm
0             1.0000
1             0.1667
2             0.6806
3             0.3472
4             0.8750
5             0.5694
6             0.2917
7             0.0139
8             0.0556
9             0.2083
10            0.2361
11            0.0000
12            0.1389
13            0.0278
14            0.0000
15            0.0139
16            0.0556
17            0.0000
18            0.0000
19            0.0000
20            0.0000
21            0.0278

### Addding rolling features from Autralian, Chinese and Japan races

In [15]:
# ── Finish positions ──────────────────────────────────────────────────────────
aus_finish = {
    "RUS": 1,  "ANT": 2,  "LEC": 3,  "HAM": 4,
    "NOR": 5,  "VER": 6,  "BEA": 7,  "LIN": 8,
    "BOR": 9,  "GAS": 10, "OCO": 11, "ALB": 12,
    "LAW": 13, "COL": 14, "SAI": 15, "PER": 16,
    "STR": 17, "ALO": 18, "BOT": 19, "HAD": 20,
    "PIA": 21, "HUL": 22,
}

china_finish = {
    "ANT": 1,  "RUS": 2,  "HAM": 3,  "LEC": 4,
    "BEA": 5,  "GAS": 6,  "LAW": 7,  "HAD": 8,
    "SAI": 9,  "COL": 10, "HUL": 11, "LIN": 12,
    "BOT": 13, "OCO": 14, "PER": 15, "VER": 16,
    "ALO": 17, "STR": 18, "NOR": 19, "BOR": 20,
    "ALB": 21, "PIA": 22,
}

# Japan GP final classification (confirmed, The Race / PlanetF1 / ESPN)
japan_finish = {
    "ANT": 1,  "PIA": 2,  "LEC": 3,  "RUS": 4,
    "NOR": 5,  "HAM": 6,  "GAS": 7,  "VER": 8,
    "LAW": 9,  "OCO": 10, "HUL": 11, "HAD": 12,
    "BOR": 13, "LIN": 14, "SAI": 15, "COL": 16,
    "PER": 17, "ALO": 18, "BOT": 19, "ALB": 20,
    "STR": 21, "BEA": 22,   # STR DNF, BEA DNF → ranked last
}

# ── Grid / qualifying positions ───────────────────────────────────────────────
aus_grid = {
    "RUS": 1,  "ANT": 2,  "HAD": 3,  "LEC": 4,  "PIA": 5,
    "NOR": 6,  "HAM": 7,  "LAW": 8,  "LIN": 9,  "BOR": 10,
    "OCO": 11, "HUL": 12, "ALB": 13, "GAS": 14, "COL": 15,
    "BEA": 16, "ALO": 17, "PER": 18, "BOT": 19, "VER": 20,
    "SAI": 21, "STR": 22,
}

china_grid = {
    "ANT": 1,  "RUS": 2,  "HAM": 3,  "LEC": 4,  "PIA": 5,
    "NOR": 6,  "GAS": 7,  "VER": 8,  "HAD": 9,  "BEA": 10,
    "HUL": 11, "COL": 12, "OCO": 13, "LAW": 14, "LIN": 15,
    "BOR": 16, "SAI": 17, "ALB": 18, "ALO": 19, "BOT": 20,
    "STR": 21, "PER": 22,
}

# Japan qualifying grid (confirmed, The Race / RacingNews365)
japan_grid = {
    "ANT": 1,  "RUS": 2,  "PIA": 3,  "LEC": 4,  "NOR": 5,
    "HAM": 6,  "GAS": 7,  "HAD": 8,  "BOR": 9,  "LIN": 10,
    "VER": 11, "OCO": 12, "HUL": 13, "LAW": 14, "COL": 15,
    "SAI": 16, "ALB": 17, "BEA": 18, "PER": 19, "BOT": 20,
    "ALO": 21, "STR": 22,
}

# ── Constructor standings after Japan (R3) ────────────────────────────────────
# Source: pitdebrief.com / racingnews365.com
team_points = {
    "Mercedes":     135,
    "Ferrari":       90,
    "McLaren":       46,
    "Haas":          18,
    "Red Bull":      16,
    "Alpine":        16,
    "Racing Bulls":  15,
    "Audi":           2,
    "Williams":       1,
    "Cadillac":       0,
    "Aston Martin":   0,
}

driver_to_team = {
    "RUS": "Mercedes",     "ANT": "Mercedes",
    "HAM": "Ferrari",      "LEC": "Ferrari",
    "NOR": "McLaren",      "PIA": "McLaren",
    "VER": "Red Bull",     "HAD": "Red Bull",
    "BEA": "Haas",         "OCO": "Haas",
    "LAW": "Racing Bulls", "LIN": "Racing Bulls",
    "HUL": "Audi",         "BOR": "Audi",
    "GAS": "Alpine",       "COL": "Alpine",
    "SAI": "Williams",     "ALB": "Williams",
    "PER": "Cadillac",     "BOT": "Cadillac",
    "ALO": "Aston Martin", "STR": "Aston Martin",
}

# ── Build 3-race rolling features ─────────────────────────────────────────────
drivers = list(driver_to_team.keys())
N = len(drivers)  # 22

records = []
for drv in drivers:
    aus_fp  = aus_finish[drv];   chn_fp  = china_finish[drv]; jpn_fp  = japan_finish[drv]
    aus_gp  = aus_grid[drv];     chn_gp  = china_grid[drv];   jpn_gp  = japan_grid[drv]

    avg_finish_pos  = round((aus_fp + chn_fp + jpn_fp) / 3, 2)
    avg_finish_norm = round(((aus_fp-1)/(N-1) + (chn_fp-1)/(N-1) + (jpn_fp-1)/(N-1)) / 3, 4)

    avg_grid_pos  = round((aus_gp + chn_gp + jpn_gp) / 3, 2)
    avg_grid_norm = round(((aus_gp-1)/(N-1) + (chn_gp-1)/(N-1) + (jpn_gp-1)/(N-1)) / 3, 4)

    # DNF: STR & BEA in Japan, VER & ALO & STR (DNF) in China, PIA & HUL in Aus
    dnf_aus = 1 if aus_fp >= 18 else 0
    dnf_chn = 1 if chn_fp >= 16 else 0
    dnf_jpn = 1 if jpn_fp >= 21 else 0   # STR=21, BEA=22 DNF
    dnf_rate = round((dnf_aus + dnf_chn + dnf_jpn) / 3, 3)

    records.append({
        "Driver":        drv,
        "Team":          driver_to_team[drv],
        "AusFinish":     aus_fp, "ChinaFinish": chn_fp, "JapanFinish": jpn_fp,
        "AvgFinishPos":  avg_finish_pos,
        "AvgFinishNorm": avg_finish_norm,
        "AusGrid":       aus_gp, "ChinaGrid": chn_gp, "JapanGrid_prev": jpn_gp,
        "AvgGridPos":    avg_grid_pos,
        "AvgGridNorm":   avg_grid_norm,
        "DNF_rate":      dnf_rate,
    })

rolling_df = pd.DataFrame(records)

max_team_pts   = max(team_points.values())
max_driver_pts = max(driver_points.values())

rolling_df["TeamScore"] = rolling_df["Team"].map(
    {t: max(p, 0.5) / max_team_pts for t, p in team_points.items()}
).round(4)

rolling_df["DriverPointsNorm"] = rolling_df["Driver"].map(
    {d: p / max_driver_pts for d, p in driver_points.items()}
).round(4)

print("\n" + "=" * 90)
print("  ROLLING FEATURES FOR MIAMI GP PREDICTION")
print("  Based on: Australia (R1) + China (R2) + Japan (R3)")
print("=" * 90)
print(f"\n{'DRV':<6}{'Team':<16}{'AUS':<5}{'CHN':<5}{'JPN':<5}{'AvgFin':<9}"
      f"{'AvgFinNorm':<12}{'AvgGrid':<9}{'AvgGridNorm':<13}"
      f"{'DNF%':<7}{'TeamScore':<11}{'DrvPtsNorm'}")
print("─" * 105)
for _, r in rolling_df.sort_values("AvgFinishPos").iterrows():
    print(f"{r['Driver']:<6}{r['Team']:<16}{r['AusFinish']:<5}{r['ChinaFinish']:<5}"
          f"{r['JapanFinish']:<5}{r['AvgFinishPos']:<9}{r['AvgFinishNorm']:<12}"
          f"{r['AvgGridPos']:<9}{r['AvgGridNorm']:<13}{r['DNF_rate']:<7}"
          f"{r['TeamScore']:<11}{r['DriverPointsNorm']}")

# ── Load Miami Sprint race pace (Miami is a Sprint weekend — no FP2) ──────────
# The Sprint race gives the best available race-pace signal for the GP.
# We use ALL classified Sprint laps (typically ~19 laps) filtered to:
#   - IsAccurate == True
#   - Within 107% of the driver's own median (removes SC/VSC laps)
#   - Any compound (Sprint tyre choice is less constrained)
session_spr = fastf1.get_session(2026, "Miami", "Sprint")
session_spr.load(telemetry=False, weather=False, messages=False)

spr_laps = session_spr.laps.copy()
spr_laps["LapTime_s"] = spr_laps["LapTime"].apply(td_to_s)
spr_laps = spr_laps[spr_laps["IsAccurate"] == True]

def within_107(group):
    med = group["LapTime_s"].median()
    return group[group["LapTime_s"] <= med * 1.07]

spr_laps = spr_laps.groupby("Driver", group_keys=False).apply(within_107)

fp2_records = []
for driver, grp in spr_laps.groupby("Driver"):
    fp2_records.append({
        "Driver":           driver,
        "FP2_MedianPace_s": round(grp["LapTime_s"].median(), 3),
        "FP2_MeanPace_s":   round(grp["LapTime_s"].mean(),   3),
        "FP2_BestPace_s":   round(grp["LapTime_s"].min(),    3),
        "FP2_LapCount":     len(grp),
        "FP2_Compounds":    str(grp["Compound"].value_counts().to_dict()),
    })

fp2_df = pd.DataFrame(fp2_records).sort_values("FP2_MedianPace_s").reset_index(drop=True)
ref_pace = fp2_df["FP2_MedianPace_s"].min()
fp2_df["FP2_GapToFastest_s"] = (fp2_df["FP2_MedianPace_s"] - ref_pace).round(3)

print("\nSprint race pace (proxy for GP long-run pace):")
print(fp2_df[["Driver", "FP2_MedianPace_s", "FP2_GapToFastest_s",
              "FP2_LapCount", "FP2_Compounds"]])

# ── Merge all data ────────────────────────────────────────────────────────────
df = quali_df.merge(
    rolling_df[["Driver", "AvgFinishNorm", "AvgGridNorm",
                "DNF_rate", "TeamScore", "Team"]],
    on="Driver", how="left"
)

df_final = df.merge(
    fp2_df[["Driver", "FP2_GapToFastest_s"]],
    on="Driver", how="left"
)

core           INFO 	Loading data for Miami Grand Prix - Sprint [v3.8.3]
INFO:fastf1.fastf1.core:Loading data for Miami Grand Prix - Sprint [v3.8.3]
req            INFO 	No cached data found for session_info. Loading data...
INFO:fastf1.fastf1.req:No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
INFO:fastf1.api:Fetching session info data...

==========================================================================================
  ROLLING FEATURES FOR MIAMI GP PREDICTION
  Based on: Australia (R1) + China (R2) + Japan (R3)
==========================================================================================

DRV   Team            AUS  CHN  JPN  AvgFin   AvgFinNorm  AvgGrid  AvgGridNorm  DNF%   TeamScore  DrvPtsNorm
─────────────────────────────────────────────────────────────────────────────────────────────────────────
ANT   Mercedes        2    1    1    1.33     0.0159      1.33     0.0159       0.0    1.0        1.0
RUS   Mercedes        1    2    4    2.33     0.0635      1.67     0.0317       0.0    1.0        0.875
LEC   Ferrari         3    4    3    3.33     0.1111      4.0      0.1429       0.0    0.6667     0.6806
HAM   Ferrari         4    3    6    4.33     0.1587      5.33     0.2063       0.0    0.6667     0.5694
GAS   Alpine          10   6    7    7.67     0.3175      9.33     0.3968       0.0    0.1185     0.2083
NOR   McLaren         5    19   5    9.67     0.4127      5.67     0.2222       0.333  0.3407     0.3472
LAW   Racing Bulls    13   7    9    9.67     0.4127      12.0     0.5238       0.0    0.1111     0.1389
VER   Red Bull        6    16   8    10.0     0.4286      13.0     0.5714       0.333  0.1185     0.1667
LIN   Racing Bulls    8    12   14   11.33    0.4921      11.33    0.4921       0.0    0.1111     0.0556
BEA   Haas            7    5    22   11.33    0.4921      14.67    0.6508       0.333  0.1333     0.2361
OCO   Haas            11   14   10   11.67    0.5079      12.0     0.5238       0.0    0.1333     0.0139
SAI   Williams        15   9    15   13.0     0.5714      18.0     0.8095       0.0    0.0074     0.0278
COL   Alpine          14   10   16   13.33    0.5873      14.0     0.619        0.0    0.1185     0.0139
HAD   Red Bull        20   8    12   13.33    0.5873      6.67     0.2698       0.333  0.1185     0.0556
BOR   Audi            9    20   13   14.0     0.619       11.67    0.5079       0.333  0.0148     0.0278
HUL   Audi            22   11   11   14.67    0.6508      12.0     0.5238       0.333  0.0148     0.0
PIA   McLaren         21   22   2    15.0     0.6667      4.33     0.1587       0.667  0.3407     0.2917
PER   Cadillac        16   15   17   16.0     0.7143      19.67    0.8889       0.0    0.0037     0.0
BOT   Cadillac        19   13   19   17.0     0.7619      19.67    0.8889       0.333  0.0037     0.0
ALB   Williams        12   21   20   17.67    0.7937      16.0     0.7143       0.333  0.0074     0.0
ALO   Aston Martin    18   17   18   17.67    0.7937      19.0     0.8571       0.667  0.0037     0.0
STR   Aston Martin    17   18   21   18.67    0.8413      21.67    0.9841       0.667  0.0037     0.0

req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
INFO:fastf1.fastf1.req:No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
INFO:fastf1.api:Fetching driver list...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
INFO:fastf1.api:Fetching session status data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for lap_count. Loading data...
INFO:fastf1.fastf1.req:No cached data found for lap_count. Loading data...
_api           INFO 	Fetching lap count data...
INFO:fastf1.api:Fetching lap count data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
INFO:fastf1.api:Fetching track status data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
INFO:fastf1.api:Fetching timing data...
_api           INFO 	Parsing timing data...
INFO:fastf1.api:Parsing timing data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
INFO:fastf1.api:Fetching timing app data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
core           INFO 	Processing timing data...
INFO:fastf1.fastf1.core:Processing timing data...
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 27)
WARNING:fastf1.fastf1.core:Failed to perform lap accuracy check - all laps marked as inaccurate (driver 27)
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 41)
WARNING:fastf1.fastf1.core:Failed to perform lap accuracy check - all laps marked as inaccurate (driver 41)
core           INFO 	Finished loading data for 22 drivers: ['1', '81', '16', '63', '3', '12', '44', '10', '6', '43', '31', '87', '55', '30', '14', '11', '18', '23', '77', '27', '41', '5']
INFO:fastf1.fastf1.core:Finished loading data for 22 drivers: ['1', '81', '16', '63', '3', '12', '44', '10', '6', '43', '31', '87', '55', '30', '14', '11', '18', '23', '77', '27', '41', '5']

Sprint race pace (proxy for GP long-run pace):
   Driver  FP2_MedianPace_s  FP2_GapToFastest_s  FP2_LapCount   FP2_Compounds
0     NOR            92.219               0.000            18  {'MEDIUM': 18}
1     LEC            92.425               0.206            18  {'MEDIUM': 18}
2     PIA            92.437               0.218            18  {'MEDIUM': 18}
3     ANT            92.571               0.352            18  {'MEDIUM': 18}
4     VER            92.623               0.404            18  {'MEDIUM': 18}
5     RUS            92.692               0.473            18  {'MEDIUM': 18}
6     HAM            92.978               0.759            18  {'MEDIUM': 18}
7     GAS            93.665               1.446            18  {'MEDIUM': 18}
8     HAD            93.727               1.508            18  {'MEDIUM': 18}
9     COL            93.950               1.731            18  {'MEDIUM': 18}
10    ALB            94.094               1.875            16  {'MEDIUM': 16}
11    BOR            94.480               2.261            18  {'MEDIUM': 18}
12    LAW            94.575               2.356            18  {'MEDIUM': 18}
13    SAI            94.966               2.747            18  {'MEDIUM': 18}
14    BEA            95.000               2.781            18  {'MEDIUM': 18}
15    OCO            95.007               2.788            18  {'MEDIUM': 18}
16    ALO            95.829               3.610            18    {'SOFT': 18}
17    PER            95.851               3.632            18    {'HARD': 18}
18    STR            95.880               3.661            18    {'SOFT': 18}
19    BOT            96.631               4.412            18    {'HARD': 18}

/tmp/ipykernel_13475/2830228681.py:163: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  spr_laps = spr_laps.groupby("Driver", group_keys=False).apply(within_107)

### Feature Engineering

In [16]:
feature_cols = [
    "UltimateLap_s",        # Miami quali: best S1+S2+S3
    "MiamiGapFromPole_s",   # Miami quali: gap to pole
    "MiamiGrid",            # Miami qualifying position
    "FP2_GapToFastest_s",   # FP2 long-run race pace
    "TeamScore",            # Constructor points normalised (after Japan R3)
    "DriverPointsNorm",     # Driver points normalised (after Japan R3)
    "AvgFinishNorm",        # Rolling avg finish (Aus + China + Japan)
    "AvgGridNorm",          # Rolling avg grid (Aus + China + Japan)
    "DNF_rate",             # Reliability signal (3 races)
    "RainProbability",      # Weather: 40% race day rain
    "Temperature",          # Weather: ~28°C
]

# ── Target variable: rolling normalised race score ────────────────────────────
df_final["RaceScore"] = (
    0.6 * df_final["AvgFinishNorm"] +
    0.4 * df_final["AvgGridNorm"]
).round(4)

X = df_final[feature_cols].copy()
y = df_final["RaceScore"]

imputer   = SimpleImputer(strategy="median")
X_imputed = imputer.fit_transform(X)

### Modelling

In [18]:
# ── Multi-model LOO-CV comparison ─────────────────────────────────────────────
models = {
    "Ridge":         Ridge(alpha=1.0),
    "ElasticNet":    ElasticNet(alpha=0.1, l1_ratio=0.5),
    "RandomForest":  RandomForestRegressor(
                         n_estimators=100, max_depth=3,
                         min_samples_leaf=3, random_state=42),
    "GradientBoost": GradientBoostingRegressor(
                         n_estimators=100, learning_rate=0.05,
                         max_depth=2, subsample=0.8, random_state=42),
    "XGBoost":       XGBRegressor(
                         n_estimators=100, learning_rate=0.05,
                         max_depth=2, subsample=0.8,
                         colsample_bytree=0.8, reg_lambda=2.0,
                         random_state=42),
}

loo     = LeaveOneOut()
results = {}

for name, mdl in models.items():
    pipe = (Pipeline([("scaler", StandardScaler()), ("model", mdl)])
            if name in ["Ridge", "ElasticNet"]
            else Pipeline([("model", mdl)]))
    errors = []
    for train_idx, test_idx in loo.split(X_imputed):
        pipe.fit(X_imputed[train_idx], y.iloc[train_idx])
        errors.append(abs(pipe.predict(X_imputed[test_idx])[0] - y.iloc[test_idx].iloc[0]))
    results[name] = {"MAE": round(np.mean(errors), 4), "StdDev": round(np.std(errors), 4)}

print(f"\n{'Model':<18} {'LOO MAE':>8} {'Std Dev':>8}  {'Verdict'}")
print("─" * 55)
for name, res in sorted(results.items(), key=lambda x: x[1]["MAE"]):
    best = " ← best" if res["MAE"] == min(r["MAE"] for r in results.values()) else ""
    print(f"{name:<18} {res['MAE']:>8.4f} {res['StdDev']:>8.4f}  {best}")

# ── Best model final prediction ───────────────────────────────────────────────
best_name  = min(results, key=lambda x: results[x]["MAE"])
best_model = models[best_name]
final_pipe = (Pipeline([("scaler", StandardScaler()), ("model", best_model)])
              if best_name in ["Ridge", "ElasticNet"]
              else Pipeline([("model", best_model)]))
final_pipe.fit(X_imputed, y)
df_final["PredictedScore"] = final_pipe.predict(X_imputed)

final = df_final.sort_values("PredictedScore").reset_index(drop=True)

print("\n" + "=" * 70)
print("   PREDICTED FINISHING ORDER — 2026 MIAMI GRAND PRIX")
print("   Rolling target: Aus + China + Japan avg finish + avg grid")
print("=" * 70)
print(f"  {'P':<4}{'DRV':<6}{'Team':<22}{'Score'}")
print("  " + "─" * 45)
for i, row in final.iterrows():
    print(f"  {i+1:<4}{row['Driver']:<6}{row['Team']:<22}{row['PredictedScore']:.4f}")

podium = final.head(3)
print(f"\n  {'='*50}")
print(f"  🥇 P1: {podium.iloc[0]['Driver']} ({podium.iloc[0]['Team']})")
print(f"  🥈 P2: {podium.iloc[1]['Driver']} ({podium.iloc[1]['Team']})")
print(f"  🥉 P3: {podium.iloc[2]['Driver']} ({podium.iloc[2]['Team']})")
print(f"\n  Best model:   {best_name}")
print(f"  LOO MAE:      {results[best_name]['MAE']:.4f}")
print(f"  LOO Std Dev:  {results[best_name]['StdDev']:.4f}")
print(f"  Weather:      {df_final['Temperature'].iloc[0]:.1f}°C | Rain: {df_final['RainProbability'].iloc[0]:.0%}")
print(f"  {'='*50}")

# ── Feature importances ───────────────────────────────────────────────────────
if best_name in ["RandomForest", "GradientBoost", "XGBoost"]:
    importances = final_pipe.named_steps["model"].feature_importances_
    print("\nFeature importances:")
    for feat, imp in sorted(zip(feature_cols, importances), key=lambda x: -x[1]):
        bar = "█" * int(imp * 50)
        print(f"  {feat:<28} {imp:.4f}  {bar}")
elif best_name in ["Ridge", "ElasticNet"]:
    coefficients = final_pipe.named_steps["model"].coef_
    print("\nFeature coefficients:")
    for feat, coef in sorted(zip(feature_cols, coefficients), key=lambda x: -abs(x[1])):
        bar = "█" * int(abs(coef) * 20)
        print(f"  {feat:<28} {coef:+.4f}  {bar}")

# ── All-models side-by-side comparison ───────────────────────────────────────
all_predictions = {}
for name, mdl in models.items():
    pipe = (Pipeline([("scaler", StandardScaler()), ("model", mdl)])
            if name in ["Ridge", "ElasticNet"]
            else Pipeline([("model", mdl)]))
    pipe.fit(X_imputed, y)
    ranked = pd.Series(pipe.predict(X_imputed),
                       index=df_final["Driver"]).rank(method="min").astype(int)
    all_predictions[name] = ranked

pred_df = pd.DataFrame(all_predictions)
pred_df["BestModelPos"] = pd.Series(
    final_pipe.predict(X_imputed), index=df_final["Driver"]
).rank(method="min").astype(int)
pred_df = pred_df.sort_values("BestModelPos")

print("\n" + "=" * 95)
print("   PREDICTED FINISHING ORDER — 2026 MIAMI GRAND PRIX  (all models)")
print("=" * 95)
col_w  = 14
header = f"  {'DRV':<6}{'Team':<22}"
for name in models: header += f"{name:>{col_w}}"
header += f"  {'★ Best':>{col_w}}"
print(header)
print("  " + "─" * 88)
for driver in pred_df.index:
    team = df_final.loc[df_final["Driver"] == driver, "Team"].values[0]
    row  = f"  {driver:<6}{team:<22}"
    for name in models:
        row += f"  P{pred_df.loc[driver, name]:<{col_w-2}}"
    row += f"  P{pred_df.loc[driver, 'BestModelPos']:<{col_w-2}}"
    print(row)

# ── Consensus podium ──────────────────────────────────────────────────────────
best_order = pred_df.sort_values("BestModelPos")
p1, p2, p3 = best_order.index[0], best_order.index[1], best_order.index[2]
t1 = df_final.loc[df_final["Driver"] == p1, "Team"].values[0]
t2 = df_final.loc[df_final["Driver"] == p2, "Team"].values[0]
t3 = df_final.loc[df_final["Driver"] == p3, "Team"].values[0]

print(f"\n  {'='*58}")
print(f"  Best model: {best_name} (LOO MAE: {results[best_name]['MAE']:.4f})")
print(f"  🥇 P1: {p1} ({t1})")
print(f"  🥈 P2: {p2} ({t2})")
print(f"  🥉 P3: {p3} ({t3})")
print(f"  Weather: {df_final['Temperature'].iloc[0]:.1f}°C | Rain: {df_final['RainProbability'].iloc[0]:.0%}")
print(f"  {'='*58}")

print("\n  CONSENSUS PODIUM (across all models):")
print("  " + "─" * 40)
medals = ["🥇", "🥈", "🥉"]
for pos in [1, 2, 3]:
    pos_counts = {}
    for name in models:
        for d in pred_df[pred_df[name] == pos].index:
            pos_counts[d] = pos_counts.get(d, 0) + 1
    if pos_counts:
        top   = max(pos_counts, key=pos_counts.get)
        votes = pos_counts[top]
        print(f"  {medals[pos-1]} P{pos}: {top} — {votes}/{len(models)} models agree")
print(f"  {'='*58}")

Model               LOO MAE  Std Dev  Verdict
───────────────────────────────────────────────────────
Ridge                0.0196   0.0185   ← best
GradientBoost        0.0398   0.0318
ElasticNet           0.0499   0.0403
XGBoost              0.0601   0.0561
RandomForest         0.0717   0.0569

======================================================================
   PREDICTED FINISHING ORDER — 2026 MIAMI GRAND PRIX
   Rolling target: Aus + China + Japan avg finish + avg grid
======================================================================
  P   DRV   Team                  Score
  ─────────────────────────────────────────────
  1   ANT   Mercedes              0.0084
  2   RUS   Mercedes              0.0496
  3   LEC   Ferrari               0.1260
  4   HAM   Ferrari               0.1862
  5   NOR   McLaren               0.3352
  6   GAS   Alpine                0.3732
  7   PIA   McLaren               0.4553
  8   LAW   Racing Bulls          0.4744
  9   HAD   Red Bull              0.4783
  10  VER   Red Bull              0.4830
  11  LIN   Racing Bulls          0.4983
  12  OCO   Haas                  0.5308
  13  BEA   Haas                  0.5696
  14  COL   Alpine                0.5735
  15  BOR   Audi                  0.5890
  16  HUL   Audi                  0.6028
  17  SAI   Williams              0.6530
  18  ALB   Williams              0.7299
  19  PER   Cadillac              0.7597
  20  BOT   Cadillac              0.8092
  21  ALO   Aston Martin          0.8251
  22  STR   Aston Martin          0.8894

  ==================================================
  🥇 P1: ANT (Mercedes)
  🥈 P2: RUS (Mercedes)
  🥉 P3: LEC (Ferrari)

  Best model:   Ridge
  LOO MAE:      0.0196
  LOO Std Dev:  0.0185
  Weather:      28.0°C | Rain: 40%
  ==================================================

Feature coefficients:
  AvgFinishNorm                +0.0972  █
  AvgGridNorm                  +0.0950  █
  DriverPointsNorm             -0.0219
  DNF_rate                     +0.0180
  FP2_GapToFastest_s           +0.0170
  TeamScore                    -0.0105
  UltimateLap_s                -0.0085
  MiamiGrid                    +0.0082
  MiamiGapFromPole_s           +0.0047
  RainProbability              +0.0000
  Temperature                  +0.0000

===============================================================================================
   PREDICTED FINISHING ORDER — 2026 MIAMI GRAND PRIX  (all models)
===============================================================================================
  DRV   Team                           Ridge    ElasticNet  RandomForest GradientBoost       XGBoost          ★ Best
  ────────────────────────────────────────────────────────────────────────────────────────
  ANT   Mercedes                P1             P1             P1             P1             P1             P1
  RUS   Mercedes                P2             P2             P1             P2             P2             P2
  LEC   Ferrari                 P3             P3             P1             P3             P3             P3
  HAM   Ferrari                 P4             P4             P4             P4             P4             P4
  NOR   McLaren                 P5             P5             P5             P5             P5             P5
  GAS   Alpine                  P6             P6             P6             P6             P6             P6
  PIA   McLaren                 P7             P8             P8             P8             P9             P7
  LAW   Racing Bulls            P8             P7             P9             P7             P7             P8
  HAD   Red Bull                P9             P9             P10            P9             P8             P9
  VER   Red Bull                P10            P10            P7             P10            P10            P10
  LIN   Racing Bulls            P11            P11            P11            P11            P11            P11
  OCO   Haas                    P12            P12            P13            P12            P12            P12
  BEA   Haas                    P13            P13            P12            P13            P13            P13
  COL   Alpine                  P14            P15            P14            P16            P16            P14
  BOR   Audi                    P15            P14            P15            P14            P14            P15
  HUL   Audi                    P16            P16            P16            P15            P15            P16
  SAI   Williams                P17            P17            P17            P17            P17            P17
  ALB   Williams                P18            P18            P18            P18            P18            P18
  PER   Cadillac                P19            P19            P19            P19            P19            P19
  BOT   Cadillac                P20            P20            P20            P20            P20            P20
  ALO   Aston Martin            P21            P21            P20            P21            P21            P21
  STR   Aston Martin            P22            P22            P20            P22            P22            P22

  ==========================================================
  Best model: Ridge (LOO MAE: 0.0196)
  🥇 P1: ANT (Mercedes)
  🥈 P2: RUS (Mercedes)
  🥉 P3: LEC (Ferrari)
  Weather: 28.0°C | Rain: 40%
  ==========================================================

  CONSENSUS PODIUM (across all models):
  ────────────────────────────────────────
  🥇 P1: ANT — 5/5 models agree
  🥈 P2: RUS — 4/5 models agree
  🥉 P3: LEC — 4/5 models agree
  ==========================================================

### Pulling requests from Fast F1 API

In [ ]:
import sys
print(sys.executable)

/usr/bin/python3

In [ ]:
import sys
!{sys.executable} -m pip install fastf1

Collecting fastf1
  Downloading fastf1-3.8.2-py3-none-any.whl.metadata (5.1 kB)
Requirement already satisfied: cryptography in /usr/local/lib/python3.12/dist-packages (from fastf1) (43.0.3)
Requirement already satisfied: matplotlib<4.0.0,>=3.8.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (3.10.0)
Requirement already satisfied: numpy<3.0.0,>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.0.2)
Requirement already satisfied: pandas<3.0.0,>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.2.2)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.12/dist-packages (from fastf1) (4.9.6)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.12.3)
Requirement already satisfied: pyjwt in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.12.1)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.9.0.post0)
Collecting rapidfuzz (from fastf1)
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Collecting requests-cache>=1.0.0 (from fastf1)
  Downloading requests_cache-1.3.1-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: requests>=2.30.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (2.32.4)
Requirement already satisfied: scipy<2.0.0,>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from fastf1) (1.16.3)
Collecting signalrcore (from fastf1)
  Downloading signalrcore-1.0.2-py3-none-any.whl.metadata (13 kB)
Collecting timple>=0.1.6 (from fastf1)
  Downloading timple-0.1.8-py3-none-any.whl.metadata (2.0 kB)
Requirement already satisfied: websockets>=10.3 in /usr/local/lib/python3.12/dist-packages (from fastf1) (15.0.1)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.1.1->fastf1) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3.0.0,>=2.1.1->fastf1) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil->fastf1) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.30.0->fastf1) (2026.2.25)
Requirement already satisfied: attrs>=21.2 in /usr/local/lib/python3.12/dist-packages (from requests-cache>=1.0.0->fastf1) (26.1.0)
Collecting cattrs>=22.2 (from requests-cache>=1.0.0->fastf1)
  Downloading cattrs-26.1.0-py3-none-any.whl.metadata (8.5 kB)
Collecting url-normalize>=2.0 (from requests-cache>=1.0.0->fastf1)
  Downloading url_normalize-2.2.1-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography->fastf1) (2.0.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->fastf1) (0.4.2)
Requirement already satisfied: msgpack==1.1.2 in /usr/local/lib/python3.12/dist-packages (from signalrcore->fastf1) (1.1.2)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography->fastf1) (3.0)
Downloading fastf1-3.8.2-py3-none-any.whl (135 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.4/135.4 kB 5.6 MB/s eta 0:00:00
Downloading requests_cache-1.3.1-py3-none-any.whl (70 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.2/70.2 kB 6.1 MB/s eta 0:00:00
Downloading timple-0.1.8-py3-none-any.whl (17 kB)
Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 62.9 MB/s eta 0:00:00:00:01
Downloading signalrcore-1.0.2-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.6/55.6 kB 4.1 MB/s eta 0:00:00
Downloading cattrs-26.1.0-py3-none-any.whl (73 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 6.4 MB/s eta 0:00:00
Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Installing collected packages: url-normalize, signalrcore, rapidfuzz, cattrs, requests-cache, timple, fastf1
Successfully installed cattrs-26.1.0 fastf1-3.8.2 rapidfuzz-3.14.5 requests-cache-1.3.1 signalrcore-1.0.2 timple-0.1.8 url-normalize-2.2.1

In [ ]:
import fastf1
import pandas as pd

import numpy as np
import os

In [ ]:
# ── Load the session ──────────────────────────────────────────────────────────
session = fastf1.get_session(2026, "Japan", "Q")
session.load(telemetry=False, weather=True, messages=False)

laps = session.laps

req         WARNING 	DEFAULT CACHE ENABLED! (24.0 KB) /root/.cache/fastf1
WARNING:fastf1.fastf1.req:DEFAULT CACHE ENABLED! (24.0 KB) /root/.cache/fastf1
core           INFO 	Loading data for Japanese Grand Prix - Qualifying [v3.8.2]
INFO:fastf1.fastf1.core:Loading data for Japanese Grand Prix - Qualifying [v3.8.2]
req            INFO 	No cached data found for session_info. Loading data...
INFO:fastf1.fastf1.req:No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
INFO:fastf1.api:Fetching session info data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
INFO:fastf1.fastf1.req:No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
INFO:fastf1.api:Fetching driver list...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
INFO:fastf1.api:Fetching session status data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
INFO:fastf1.api:Fetching track status data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
INFO:fastf1.api:Fetching timing data...
_api           INFO 	Parsing timing data...
INFO:fastf1.api:Parsing timing data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
INFO:fastf1.api:Fetching timing app data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
core           INFO 	Processing timing data...
INFO:fastf1.fastf1.core:Processing timing data...
req            INFO 	No cached data found for weather_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
INFO:fastf1.api:Fetching weather data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['12', '63', '81', '16', '1', '44', '10', '6', '5', '41', '3', '31', '27', '30', '43', '55', '23', '87', '11', '77', '14', '18']
INFO:fastf1.fastf1.core:Finished loading data for 22 drivers: ['12', '63', '81', '16', '1', '44', '10', '6', '5', '41', '3', '31', '27', '30', '43', '55', '23', '87', '11', '77', '14', '18']

In [ ]:
# ── Best individual sector times per driver (ultimate lap) ────────────────────
# FastF1 stores sector times as timedeltas — convert to seconds
def td_to_s(td):
    """Convert timedelta (or NaT) to float seconds."""
    if pd.isnull(td):
        return np.nan
    return td.total_seconds()

records = []
for driver in laps["Driver"].unique():
    drv_all = laps.pick_drivers(driver).pick_wo_box()
    
    if drv_all.empty:
        continue  # skip drivers with no valid laps

    best_s1 = drv_all["Sector1Time"].dropna().min()
    best_s2 = drv_all["Sector2Time"].dropna().min()
    best_s3 = drv_all["Sector3Time"].dropna().min()
    best_lap = drv_all["LapTime"].dropna().min()  # ← get best lap directly

    records.append({
        "Driver":    driver,
        "S1":        td_to_s(best_s1),
        "S2":        td_to_s(best_s2),
        "S3":        td_to_s(best_s3),
        "BestLap_s": td_to_s(best_lap),
    })

quali_df = pd.DataFrame(records)

# ── Ultimate lap = S1 + S2 + S3 ───────────────────────────────────────────────
quali_df["UltimateLap_s"] = (
    quali_df["S1"] + quali_df["S2"] + quali_df["S3"]
).round(3)

# ── Gap from pole (use best Q3 / overall best lap) ───────────────────────────
pole_time = quali_df["BestLap_s"].min()
quali_df["JapanGapFromPole_s"] = (quali_df["BestLap_s"] - pole_time).round(3)

# Percentage gap — more comparable across circuits than raw seconds
quali_df["JapanGapFromPolePct"] = (
    quali_df["JapanGapFromPole_s"] / pole_time * 100
).round(4)

# ── Grid position (sort by best lap) ─────────────────────────────────────────
quali_df = quali_df.sort_values("BestLap_s").reset_index(drop=True)
quali_df["JapanGrid"] = quali_df.index + 1

# Adding The tremperature + rainfall probability on that day
# Japan GP weather — sourced manually (e.g. Weather.com / AccuWeather)
rain_probability = 0.10   # replace with actual figure
temperature      = 18.0   # replace with actual figure

quali_df["RainProbability"] = rain_probability
quali_df["Temperature"]     = temperature

# Adding the Driver points from the 2 races(Australia and Chinese GPs)
driver_points = {
    "RUS": 44, "LEC": 38, "ANT": 35, "NOR": 32, "HAM": 28,
    "PIA": 22, "VER": 18, "BEA": 14, "LIN": 12, "BOR": 10,
    "GAS": 8,  "LAW": 6,  "OCO": 4,  "ALB": 4,  "HAD": 2,
    "COL": 1,  "SAI": 0,  "ALO": 0,  "BOT": 0,
    "STR": 0,  "PER": 0,  "HUL": 0,
}

max_driver_pts = max(v for v in driver_points.values() if v > 0)
quali_df["DriverPoints"]     = quali_df["Driver"].map(driver_points).fillna(0)
quali_df["DriverPointsNorm"] = (quali_df["DriverPoints"] / max_driver_pts).round(4)


print(quali_df[["Driver", "S1", "S2", "S3", "UltimateLap_s",
                "BestLap_s", "JapanGrid", "JapanGapFromPole_s",
                "JapanGapFromPolePct", "RainProbability", "Temperature", "DriverPointsNorm"]])

quali_df.to_csv("japan_quali.csv", index=False)
print("\nSaved → japan_quali.csv")

   Driver      S1      S2      S3  UltimateLap_s  BestLap_s  JapanGrid  \
0     ANT  31.827  39.398  17.464         88.689     88.778          1
1     RUS  31.782  39.607  17.616         89.005     89.076          2
2     PIA  31.954  39.557  17.577         89.088     89.132          3
3     LEC  31.655  39.855  17.668         89.178     89.303          4
4     NOR  32.049  39.716  17.627         89.392     89.409          5
5     HAM  31.762  39.933  17.625         89.320     89.567          6
6     GAS  32.143  40.029  17.519         89.691     89.691          7
7     HAD  32.164  40.094  17.608         89.866     89.978          8
8     BOR  32.288  40.149  17.492         89.929     89.990          9
9     LIN  32.548  40.043  17.501         90.092     90.109         10
10    VER  32.369  40.196  17.565         90.130     90.262         11
11    OCO  32.481  40.048  17.700         90.229     90.309         12
12    HUL  32.400  40.181  17.564         90.145     90.358         13
13    LAW  32.791  40.175  17.529         90.495     90.495         14
14    COL  32.463  40.433  17.610         90.506     90.627         15
15    SAI  32.844  40.434  17.576         90.854     90.927         16
16    ALB  32.858  40.489  17.741         91.088     91.088         17
17    BEA  32.824  40.421  17.845         91.090     91.090         18
18    PER  33.512  40.667  18.027         92.206     92.206         19
19    BOT  33.362  40.961  17.947         92.270     92.330         20
20    ALO  33.536  41.206  17.904         92.646     92.646         21
21    STR  33.595  41.341  17.948         92.884     92.920         22

    JapanGapFromPole_s  JapanGapFromPolePct  RainProbability  Temperature  \
0                0.000               0.0000              0.1         18.0
1                0.298               0.3357              0.1         18.0
2                0.354               0.3987              0.1         18.0
3                0.525               0.5914              0.1         18.0
4                0.631               0.7108              0.1         18.0
5                0.789               0.8887              0.1         18.0
6                0.913               1.0284              0.1         18.0
7                1.200               1.3517              0.1         18.0
8                1.212               1.3652              0.1         18.0
9                1.331               1.4992              0.1         18.0
10               1.484               1.6716              0.1         18.0
11               1.531               1.7245              0.1         18.0
12               1.580               1.7797              0.1         18.0
13               1.717               1.9340              0.1         18.0
14               1.849               2.0827              0.1         18.0
15               2.149               2.4206              0.1         18.0
16               2.310               2.6020              0.1         18.0
17               2.312               2.6042              0.1         18.0
18               3.428               3.8613              0.1         18.0
19               3.552               4.0010              0.1         18.0
20               3.868               4.3569              0.1         18.0
21               4.142               4.6656              0.1         18.0

    DriverPointsNorm
0             0.7955
1             1.0000
2             0.5000
3             0.8636
4             0.7273
5             0.6364
6             0.1818
7             0.0455
8             0.2273
9             0.2727
10            0.4091
11            0.0909
12            0.0000
13            0.1364
14            0.0227
15            0.0000
16            0.0909
17            0.3182
18            0.0000
19            0.0000
20            0.0000
21            0.0000

Saved → japan_quali.csv

## Building rolling features from AUstralia and Chinese GPs

In [ ]:
# Let us build the rolling features from the average of the Australian and ChineseGPs grid positions and final race positions
aus_finish = {
    "RUS": 1,  "ANT": 2,  "LEC": 3,  "HAM": 4,
    "NOR": 5,  "VER": 6,  "BEA": 7,  "LIN": 8,
    "BOR": 9,  "GAS": 10, "OCO": 11, "ALB": 12,
    "LAW": 13, "COL": 14, "SAI": 15, "PER": 16,
    "STR": 17, "ALO": 18, "BOT": 19, "HAD": 20,
    "PIA": 21, "HUL": 22,
}

In [ ]:
# China finish positions (confirmed classification)
# DNF: VER=16, ALO=17, STR=18 | DNS: NOR=19, BOR=20, ALB=21, PIA=22
china_finish = {
    "ANT": 1,  "RUS": 2,  "HAM": 3,  "LEC": 4,
    "BEA": 5,  "GAS": 6,  "LAW": 7,  "HAD": 8,
    "SAI": 9,  "COL": 10, "HUL": 11, "LIN": 12,
    "BOT": 13, "OCO": 14, "PER": 15, "VER": 16,
    "ALO": 17, "STR": 18, "NOR": 19, "BOR": 20,
    "ALB": 21, "PIA": 22,
}

In [ ]:
# Australia grid positions (confirmed qualifying)
# VER P20 (crashed Q1), SAI P21 & STR P22 (power unit issues in quali)
aus_grid = {
    "RUS": 1,  "ANT": 2,  "HAD": 3,  "LEC": 4,  "PIA": 5,
    "NOR": 6,  "HAM": 7,  "LAW": 8,  "LIN": 9,  "BOR": 10,
    "OCO": 11, "HUL": 12, "ALB": 13, "GAS": 14, "COL": 15,
    "BEA": 16, "ALO": 17, "PER": 18, "BOT": 19, "VER": 20,
    "SAI": 21, "STR": 22,
}

In [ ]:
# China grid positions (confirmed qualifying)
# ALB P18 but started from pit lane (parc fermé modification)
china_grid = {
    "ANT": 1,  "RUS": 2,  "HAM": 3,  "LEC": 4,  "PIA": 5,
    "NOR": 6,  "GAS": 7,  "VER": 8,  "HAD": 9,  "BEA": 10,
    "HUL": 11, "COL": 12, "OCO": 13, "LAW": 14, "LIN": 15,
    "BOR": 16, "SAI": 17, "ALB": 18, "ALO": 19, "BOT": 20,
    "STR": 21, "PER": 22,
}

In [ ]:
# CONSTRUCTOR STANDINGS after China (Round 2)
# Source: formula1.com / total-motorsport.com
# ─────────────────────────────────────────────────────────────────────────────
team_points = {
    "Mercedes":     98,
    "Ferrari":      67,
    "McLaren":      18,
    "Haas":         17,
    "Red Bull":     12,
    "Racing Bulls": 12,
    "Alpine":       10,
    "Audi":          2,
    "Williams":      2,
    "Cadillac":      0,
    "Aston Martin":  0,
}

In [ ]:
# DRIVER STANDINGS after China (Round 2)
# Source: autohebdof1.com / total-motorsport.com
# ─────────────────────────────────────────────────────────────────────────────
driver_points = {
    "RUS": 51, "ANT": 47, "LEC": 34, "HAM": 33,
    "BEA": 17, "NOR": 15, "GAS":  9, "VER":  8,
    "LAW":  8, "LIN":  4, "HAD":  4, "PIA":  3,
    "SAI":  2, "BOR":  2, "COL":  1, "OCO":  0,
    "HUL":  0, "ALB":  0, "BOT":  0, "PER":  0,
    "ALO":  0, "STR":  0,
}

In [ ]:
# DRIVER → TEAM MAPPING (2026 season)
# ─────────────────────────────────────────────────────────────────────────────
driver_to_team = {
    "RUS": "Mercedes",    "ANT": "Mercedes",
    "HAM": "Ferrari",     "LEC": "Ferrari",
    "NOR": "McLaren",     "PIA": "McLaren",
    "VER": "Red Bull",    "HAD": "Red Bull",
    "BEA": "Haas",        "OCO": "Haas",
    "LAW": "Racing Bulls","LIN": "Racing Bulls",
    "HUL": "Audi",        "BOR": "Audi",
    "GAS": "Alpine",      "COL": "Alpine",
    "SAI": "Williams",    "ALB": "Williams",
    "PER": "Cadillac",    "BOT": "Cadillac",
    "ALO": "Aston Martin","STR": "Aston Martin",
}

In [ ]:
# BUILD ROLLING FEATURES
# ─────────────────────────────────────────────────────────────────────────────
drivers = list(driver_to_team.keys())
N = len(drivers)  # 22
 
records = []
for drv in drivers:
    aus_fp  = aus_finish[drv]
    chn_fp  = china_finish[drv]
    aus_gp  = aus_grid[drv]
    chn_gp  = china_grid[drv]
 
    # Average finish position (dense rank, so DNFs are ranked last)
    avg_finish_pos = round((aus_fp + chn_fp) / 2, 2)
 
    # Normalised average finish (0 = best, 1 = worst)
    avg_finish_norm = round(((aus_fp - 1) / (N - 1) + (chn_fp - 1) / (N - 1)) / 2, 4)
 
    # Average grid position
    avg_grid_pos = round((aus_gp + chn_gp) / 2, 2)
 
    # Normalised average grid (0 = pole, 1 = last)
    avg_grid_norm = round(((aus_gp - 1) / (N - 1) + (chn_gp - 1) / (N - 1)) / 2, 4)
 
    # DNF rate (1 race out of 2 if DNF/DNS in either)
    dnf_aus = 1 if aus_fp >= 18 else 0   # positions 18-22 = DNF or DNS
    dnf_chn = 1 if chn_fp >= 16 else 0   # VER(16), ALO(17), STR(18) DNF; NOR+ DNS
    dnf_rate = round((dnf_aus + dnf_chn) / 2, 2)
 
    records.append({
        "Driver":          drv,
        "Team":            driver_to_team[drv],
        "AusFinish":       aus_fp,
        "ChinaFinish":     chn_fp,
        "AvgFinishPos":    avg_finish_pos,
        "AvgFinishNorm":   avg_finish_norm,
        "AusGrid":         aus_gp,
        "ChinaGrid_prev":  chn_gp,
        "AvgGridPos":      avg_grid_pos,
        "AvgGridNorm":     avg_grid_norm,
        "DNF_rate":        dnf_rate,
    })
 
rolling_df = pd.DataFrame(records)

In [ ]:
# NORMALISE TEAM & DRIVER STANDINGS
# ─────────────────────────────────────────────────────────────────────────────
max_team_pts   = max(team_points.values())
max_driver_pts = max(driver_points.values())
 
rolling_df["TeamScore"]       = rolling_df["Team"].map(
    {t: max(p, 0.5) / max_team_pts for t, p in team_points.items()}
).round(4)
 
rolling_df["DriverPointsNorm"] = rolling_df["Driver"].map(
    {d: p / max_driver_pts for d, p in driver_points.items()}
).round(4)

In [ ]:
# PRINT SUMMARY TABLE
# ─────────────────────────────────────────────────────────────────────────────
print("\n" + "=" * 80)
print("  ROLLING FEATURES FOR JAPAN GP PREDICTION")
print("  Based on: Australia (R1) + China (R2)")
print("=" * 80)
print(f"\n{'DRV':<6}{'Team':<16}{'AUS':<5}{'CHN':<5}{'AvgFin':<9}"
      f"{'AvgFinNorm':<12}{'AvgGrid':<9}{'AvgGridNorm':<13}"
      f"{'DNF%':<7}{'TeamScore':<11}{'DrvPtsNorm'}")
print("─" * 100)
for _, r in rolling_df.sort_values("AvgFinishPos").iterrows():
    print(f"{r['Driver']:<6}{r['Team']:<16}{r['AusFinish']:<5}{r['ChinaFinish']:<5}"
          f"{r['AvgFinishPos']:<9}{r['AvgFinishNorm']:<12}{r['AvgGridPos']:<9}"
          f"{r['AvgGridNorm']:<13}{r['DNF_rate']:<7}{r['TeamScore']:<11}"
          f"{r['DriverPointsNorm']}")
 
rolling_df.to_csv("rolling_features_aus_china.csv", index=False)
print("\nSaved → rolling_features_aus_china.csv")

================================================================================
  ROLLING FEATURES FOR JAPAN GP PREDICTION
  Based on: Australia (R1) + China (R2)
================================================================================

DRV   Team            AUS  CHN  AvgFin   AvgFinNorm  AvgGrid  AvgGridNorm  DNF%   TeamScore  DrvPtsNorm
────────────────────────────────────────────────────────────────────────────────────────────────────
RUS   Mercedes        1    2    1.5      0.0238      1.5      0.0238       0.0    1.0        1.0
ANT   Mercedes        2    1    1.5      0.0238      1.5      0.0238       0.0    1.0        0.9216
HAM   Ferrari         4    3    3.5      0.119       5.0      0.1905       0.0    0.6837     0.6471
LEC   Ferrari         3    4    3.5      0.119       4.0      0.1429       0.0    0.6837     0.6667
BEA   Haas            7    5    6.0      0.2381      13.0     0.5714       0.0    0.1735     0.3333
GAS   Alpine          10   6    8.0      0.3333      10.5     0.4524       0.0    0.102      0.1765
LAW   Racing Bulls    13   7    10.0     0.4286      11.0     0.4762       0.0    0.1224     0.1569
LIN   Racing Bulls    8    12   10.0     0.4286      12.0     0.5238       0.0    0.1224     0.0784
VER   Red Bull        6    16   11.0     0.4762      14.0     0.619        0.5    0.1224     0.1569
COL   Alpine          14   10   12.0     0.5238      13.5     0.5952       0.0    0.102      0.0196
NOR   McLaren         5    19   12.0     0.5238      6.0      0.2381       0.5    0.1837     0.2941
SAI   Williams        15   9    12.0     0.5238      19.0     0.8571       0.0    0.0204     0.0392
OCO   Haas            11   14   12.5     0.5476      12.0     0.5238       0.0    0.1735     0.0
HAD   Red Bull        20   8    14.0     0.619       6.0      0.2381       0.5    0.1224     0.0784
BOR   Audi            9    20   14.5     0.6429      13.0     0.5714       0.5    0.0204     0.0392
PER   Cadillac        16   15   15.5     0.6905      20.0     0.9048       0.0    0.0051     0.0
BOT   Cadillac        19   13   16.0     0.7143      19.5     0.881        0.5    0.0051     0.0
HUL   Audi            22   11   16.5     0.7381      11.5     0.5          0.5    0.0204     0.0
ALB   Williams        12   21   16.5     0.7381      15.5     0.6905       0.5    0.0204     0.0
ALO   Aston Martin    18   17   17.5     0.7857      18.0     0.8095       1.0    0.0051     0.0
STR   Aston Martin    17   18   17.5     0.7857      21.5     0.9762       0.5    0.0051     0.0
PIA   McLaren         21   22   21.5     0.9762      5.0      0.1905       1.0    0.1837     0.0588

Saved → rolling_features_aus_china.csv

In [ ]:
# HOW TO MERGE INTO YOUR MAIN DATAFRAME
# ─────────────────────────────────────────────────────────────────────────────
# After building your Japan quali df, merge like this:
#
df = quali_df.merge(
    rolling_df[["Driver", "AvgFinishNorm", "AvgGridNorm",
                "DNF_rate", "TeamScore", "Team"]],
    on="Driver", how="left"
   )

In [ ]:
df.head()

,Driver,S1,S2,S3,BestLap_s,UltimateLap_s,JapanGapFromPole_s,JapanGapFromPolePct,JapanGrid,RainProbability,Temperature,DriverPoints,DriverPointsNorm,AvgFinishNorm,AvgGridNorm,DNF_rate,TeamScore,Team
0,ANT,31.827,39.398,17.464,88.778,88.689,0.000,0.0000,1,0.1,18.0,35,0.7955,0.0238,0.0238,0.0,1.0000,Mercedes
1,RUS,31.782,39.607,17.616,89.076,89.005,0.298,0.3357,2,0.1,18.0,44,1.0000,0.0238,0.0238,0.0,1.0000,Mercedes
2,PIA,31.954,39.557,17.577,89.132,89.088,0.354,0.3987,3,0.1,18.0,22,0.5000,0.9762,0.1905,1.0,0.1837,McLaren
3,LEC,31.655,39.855,17.668,89.303,89.178,0.525,0.5914,4,0.1,18.0,38,0.8636,0.1190,0.1429,0.0,0.6837,Ferrari
4,NOR,32.049,39.716,17.627,89.409,89.392,0.631,0.7108,5,0.1,18.0,32,0.7273,0.5238,0.2381,0.5,0.1837,McLaren

 ## Analysing FP2 pace for Japan

In [ ]:
# ── Load FP2 ──────────────────────────────────────────────────────────────────
session = fastf1.get_session(2026, "Japan", "FP2")
session.load(telemetry=False, weather=False, messages=False)

laps = session.laps.copy()

# ── Helper: convert timedelta to seconds ─────────────────────────────────────
def td_to_s(td):
    if pd.isnull(td):
        return np.nan
    return td.total_seconds()

laps["LapTime_s"] = laps["LapTime"].apply(td_to_s)

# ── Filter criteria ───────────────────────────────────────────────────────────
# Keep only representative race-sim laps:
#   - Not an in/out lap (IsAccurate flag or LapNumber > 1 in stint)
#   - Lap time within 110% of session median (removes outliers, VSC laps)
#   - Compound is MEDIUM or HARD (race compounds — not quali soft runs)
#   - Stint lap number >= 3 (skip initial warm-up laps)

laps = laps[laps["IsAccurate"] == True].copy()  # FastF1 flags dodgy laps

COMPOUNDS = ["MEDIUM", "HARD"]
laps = laps[laps["Compound"].isin(COMPOUNDS)]

# Stint lap number — laps within a stint counted from 1
laps["StintLapNum"] = laps.groupby(["Driver", "Stint"]).cumcount() + 1
laps = laps[laps["StintLapNum"] >= 3]

# Remove outliers: keep within 107% of driver's own median
def within_107(group):
    med = group["LapTime_s"].median()
    return group[group["LapTime_s"] <= med * 1.07]

laps = laps.groupby("Driver", group_keys=False).apply(within_107)

# ── Aggregate per driver ──────────────────────────────────────────────────────
records = []
for driver, grp in laps.groupby("Driver"):
    med_pace   = grp["LapTime_s"].median()
    mean_pace  = grp["LapTime_s"].mean()
    best_pace  = grp["LapTime_s"].min()
    lap_count  = len(grp)

    # Compound breakdown (useful for context)
    compound_counts = grp["Compound"].value_counts().to_dict()

    records.append({
        "Driver":           driver,
        "FP2_MedianPace_s": round(med_pace, 3),
        "FP2_MeanPace_s":   round(mean_pace, 3),
        "FP2_BestPace_s":   round(best_pace, 3),
        "FP2_LapCount":     lap_count,
        "FP2_Compounds":    str(compound_counts),
    })

fp2_df = pd.DataFrame(records).sort_values("FP2_MedianPace_s").reset_index(drop=True)

# ── Gap from fastest driver in FP2 ───────────────────────────────────────────
ref_pace = fp2_df["FP2_MedianPace_s"].min()
fp2_df["FP2_GapToFastest_s"] = (fp2_df["FP2_MedianPace_s"] - ref_pace).round(3)

print(fp2_df[["Driver", "FP2_MedianPace_s", "FP2_GapToFastest_s",
              "FP2_LapCount", "FP2_Compounds"]])

fp2_df.to_csv("japan_fp2_pace.csv", index=False)
print("\nSaved → japan_fp2_pace.csv")

core           INFO 	Loading data for Japanese Grand Prix - Practice 2 [v3.8.2]
INFO:fastf1.fastf1.core:Loading data for Japanese Grand Prix - Practice 2 [v3.8.2]
req            INFO 	No cached data found for session_info. Loading data...
INFO:fastf1.fastf1.req:No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
INFO:fastf1.api:Fetching session info data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
INFO:fastf1.fastf1.req:No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
INFO:fastf1.api:Fetching driver list...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for session_status_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
INFO:fastf1.api:Fetching session status data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
INFO:fastf1.api:Fetching track status data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
INFO:fastf1.api:Fetching timing data...
_api           INFO 	Parsing timing data...
INFO:fastf1.api:Parsing timing data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
INFO:fastf1.fastf1.req:No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
INFO:fastf1.api:Fetching timing app data...
req            INFO 	Data has been written to cache!
INFO:fastf1.fastf1.req:Data has been written to cache!
core           INFO 	Processing timing data...
INFO:fastf1.fastf1.core:Processing timing data...
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']
INFO:fastf1.fastf1.core:Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']

   Driver  FP2_MedianPace_s  FP2_GapToFastest_s  FP2_LapCount   FP2_Compounds
0     ANT            94.496               0.000             7   {'MEDIUM': 7}
1     STR            95.042               0.546             2   {'MEDIUM': 2}
2     RUS            95.079               0.583             6   {'MEDIUM': 6}
3     LEC            95.243               0.747             8   {'MEDIUM': 8}
4     PIA            95.808               1.312             8   {'MEDIUM': 8}
5     GAS            95.919               1.423            10    {'HARD': 10}
6     OCO            95.958               1.462            12  {'MEDIUM': 12}
7     HUL            96.146               1.650             6     {'HARD': 6}
8     HAD            96.161               1.665             9     {'HARD': 9}
9     BEA            96.170               1.674            10  {'MEDIUM': 10}
10    VER            96.299               1.803            12    {'HARD': 12}
11    HAM            96.424               1.928             3   {'MEDIUM': 3}
12    LAW            96.774               2.278             8   {'MEDIUM': 8}
13    COL            96.826               2.330            10  {'MEDIUM': 10}
14    ALB            97.219               2.723            10  {'MEDIUM': 10}
15    SAI            97.222               2.726            10    {'HARD': 10}
16    BOT            98.054               3.558            11  {'MEDIUM': 11}
17    PER            98.173               3.677             3     {'HARD': 3}
18    NOR           112.215              17.719             2   {'MEDIUM': 2}

Saved → japan_fp2_pace.csv

/tmp/ipykernel_9900/275636439.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  laps["StintLapNum"] = laps.groupby(["Driver", "Stint"]).cumcount() + 1
/tmp/ipykernel_9900/275636439.py:36: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  laps = laps.groupby("Driver", group_keys=False).apply(within_107)

In [ ]:
df_final = df.merge(
    fp2_df[["Driver", "FP2_GapToFastest_s"]],
    on="Driver", how="left"
   )

In [ ]:
df_final.head()

,Driver,S1,S2,S3,BestLap_s,UltimateLap_s,JapanGapFromPole_s,JapanGapFromPolePct,JapanGrid,RainProbability,Temperature,DriverPoints,DriverPointsNorm,AvgFinishNorm,AvgGridNorm,DNF_rate,TeamScore,Team,FP2_GapToFastest_s
0,ANT,31.827,39.398,17.464,88.778,88.689,0.000,0.0000,1,0.1,18.0,35,0.7955,0.0238,0.0238,0.0,1.0000,Mercedes,0.000
1,RUS,31.782,39.607,17.616,89.076,89.005,0.298,0.3357,2,0.1,18.0,44,1.0000,0.0238,0.0238,0.0,1.0000,Mercedes,0.583
2,PIA,31.954,39.557,17.577,89.132,89.088,0.354,0.3987,3,0.1,18.0,22,0.5000,0.9762,0.1905,1.0,0.1837,McLaren,1.312
3,LEC,31.655,39.855,17.668,89.303,89.178,0.525,0.5914,4,0.1,18.0,38,0.8636,0.1190,0.1429,0.0,0.6837,Ferrari,0.747
4,NOR,32.049,39.716,17.627,89.409,89.392,0.631,0.7108,5,0.1,18.0,32,0.7273,0.5238,0.2381,0.5,0.1837,McLaren,17.719

## Feature Engineering

In [ ]:
feature_cols = [
"UltimateLap_s",        # Japan quali: best S1+S2+S3
"JapanGapFromPole_s",   # Japan quali: gap to pole
"JapanGrid",            # Japan qualifying position
"FP2_GapToFastest_s",   # FP2 long-run race pace
"TeamScore",            # Constructor points normalised (after China)
"DriverPointsNorm",     # Driver points normalised (after China)
"AvgFinishNorm",        # Rolling avg finish (Aus + China)
"AvgGridNorm",          # Rolling avg grid (Aus + China)
"DNF_rate",             # Reliability signal
"RainProbability",      # Weather (manual)
"Temperature",          # Weather (manual)
]

In [ ]:
# Lets build our target variable
# ── Target: rolling normalised race score from Aus + China ───────────────
n_drivers = len(df_final)

# Normalise average finish position (0 = best, 1 = worst)
avg_finish_norm = df_final["AvgFinishNorm"]  # already in your df

# Normalise average grid position (0 = best, 1 = worst)  
avg_grid_norm = df_final["AvgGridNorm"]      # already in your df

# Composite target — weight finish more than grid (60/40)
df_final["RaceScore"] = (
    0.6 * avg_finish_norm +
    0.4 * avg_grid_norm
).round(4)

X = df_final[feature_cols].copy()
y = df_final["RaceScore"]

In [ ]:
import sklearn
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import mean_absolute_error
from xgboost import XGBRegressor

In [ ]:
# Filling any missing values with median
from sklearn.impute import SimpleImputer
imputer   = SimpleImputer(strategy="median")
X_imputed = imputer.fit_transform(X)

### Modelling

In [ ]:
from sklearn.linear_model import Ridge, ElasticNet
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import numpy as np

# ── Compare multiple models with LOO-CV ──────────────────────────────────────
from sklearn.model_selection import LeaveOneOut
from sklearn.metrics import mean_absolute_error

In [ ]:
models = {
    "Ridge":        Ridge(alpha=1.0),
    "ElasticNet":   ElasticNet(alpha=0.1, l1_ratio=0.5),
    "RandomForest": RandomForestRegressor(
                        n_estimators=100, max_depth=3,
                        min_samples_leaf=3, random_state=42),
    "GradientBoost": GradientBoostingRegressor(
                        n_estimators=100, learning_rate=0.05,
                        max_depth=2, subsample=0.8, random_state=42),
    "XGBoost":      XGBRegressor(
                        n_estimators=100, learning_rate=0.05,
                        max_depth=2, subsample=0.8,
                        colsample_bytree=0.8, reg_lambda=2.0,
                        random_state=42),
}

loo = LeaveOneOut()
results = {}

for name, mdl in models.items():
    # Ridge and ElasticNet benefit from scaling
    if name in ["Ridge", "ElasticNet"]:
        pipe = Pipeline([("scaler", StandardScaler()), ("model", mdl)])
    else:
        pipe = Pipeline([("model", mdl)])

    errors = []
    for train_idx, test_idx in loo.split(X_imputed):
        X_tr, X_te = X_imputed[train_idx], X_imputed[test_idx]
        y_tr, y_te = y.iloc[train_idx],    y.iloc[test_idx]
        pipe.fit(X_tr, y_tr)
        errors.append(abs(pipe.predict(X_te)[0] - y_te.iloc[0]))

    results[name] = {
        "MAE":    round(np.mean(errors), 4),
        "StdDev": round(np.std(errors), 4),
    }

In [ ]:
# ── Print comparison ──────────────────────────────────────────────────────────
print(f"\n{'Model':<18} {'LOO MAE':>8} {'Std Dev':>8}  {'Verdict'}")
print("─" * 55)
for name, res in sorted(results.items(), key=lambda x: x[1]["MAE"]):
    best = " ← best" if res["MAE"] == min(r["MAE"] for r in results.values()) else ""
    print(f"{name:<18} {res['MAE']:>8.4f} {res['StdDev']:>8.4f}  {best}")

Model               LOO MAE  Std Dev  Verdict
───────────────────────────────────────────────────────
Ridge                0.0245   0.0257   ← best
GradientBoost        0.0524   0.0615
ElasticNet           0.0584   0.0374
XGBoost              0.0687   0.0740
RandomForest         0.0806   0.0710

In [ ]:
# ── Use the best model for final prediction ───────────────────────────────────
best_name = min(results, key=lambda x: results[x]["MAE"])
print(f"\nUsing: {best_name}")

best_model = models[best_name]
if best_name in ["Ridge", "ElasticNet"]:
    final_pipe = Pipeline([("scaler", StandardScaler()), ("model", best_model)])
else:
    final_pipe = Pipeline([("model", best_model)])

final_pipe.fit(X_imputed, y)
df["PredictedScore"] = final_pipe.predict(X_imputed)

Using: Ridge

In [ ]:
final_pipe.fit(X_imputed, y)
df["PredictedScore"] = final_pipe.predict(X_imputed)

# ── Predicted finishing order ─────────────────────────────────────────────────
final = df.sort_values("PredictedScore").reset_index(drop=True)

print("\n" + "=" * 68)
print("   PREDICTED FINISHING ORDER — 2026 JAPANESE GRAND PRIX")
print("   Target: Aus + China avg finish + avg grid (rolling)")
print("=" * 68)
print(f"  {'P':<4}{'DRV':<6}{'Team':<22}{'Score'}")
print("  " + "─" * 40)
for i, row in final.iterrows():
    print(f"  {i+1:<4}{row['Driver']:<6}{row['Team']:<22}{row['PredictedScore']:.4f}")

podium = final.head(3)
print(f"\n  {'='*45}")
print(f"  🥇 P1: {podium.iloc[0]['Driver']} ({podium.iloc[0]['Team']})")
print(f"  🥈 P2: {podium.iloc[1]['Driver']} ({podium.iloc[1]['Team']})")
print(f"  🥉 P3: {podium.iloc[2]['Driver']} ({podium.iloc[2]['Team']})")
print(f"\n  Best model:        {best_name}")
print(f"  LOO MAE:           {results[best_name]['MAE']:.4f}")
print(f"  LOO Std Dev:       {results[best_name]['StdDev']:.4f}")
print(f"  Weather:           {df['Temperature'].iloc[0]:.1f}°C | Rain: {df['RainProbability'].iloc[0]:.0%}")
print(f"  {'='*45}")

# ── Feature importances (tree models only) ────────────────────────────────────
if best_name in ["RandomForest", "GradientBoost", "XGBoost"]:
    importances = final_pipe.named_steps["model"].feature_importances_
    print("\nFeature importances:")
    for feat, imp in sorted(zip(feature_cols, importances), key=lambda x: -x[1]):
        bar = "█" * int(imp * 50)
        print(f"  {feat:<28} {imp:.4f}  {bar}")
elif best_name in ["Ridge", "ElasticNet"]:
    coefficients = final_pipe.named_steps["model"].coef_
    print("\nFeature coefficients (higher = more influence):")
    for feat, coef in sorted(zip(feature_cols, coefficients), key=lambda x: -abs(x[1])):
        bar = "█" * int(abs(coef) * 20)
        print(f"  {feat:<28} {coef:+.4f}  {bar}")

====================================================================
   PREDICTED FINISHING ORDER — 2026 JAPANESE GRAND PRIX
   Target: Aus + China avg finish + avg grid (rolling)
====================================================================
  P   DRV   Team                  Score
  ────────────────────────────────────────
  1   RUS   Mercedes              0.0203
  2   ANT   Mercedes              0.0216
  3   LEC   Ferrari               0.1321
  4   HAM   Ferrari               0.1572
  5   GAS   Alpine                0.3976
  6   BEA   Haas                  0.4036
  7   NOR   McLaren               0.4130
  8   LAW   Racing Bulls          0.4638
  9   LIN   Racing Bulls          0.4646
  10  HAD   Red Bull              0.4983
  11  OCO   Haas                  0.5250
  12  VER   Red Bull              0.5311
  13  COL   Alpine                0.5479
  14  BOR   Audi                  0.6049
  15  PIA   McLaren               0.6339
  16  SAI   Williams              0.6345
  17  HUL   Audi                  0.6427
  18  ALB   Williams              0.7086
  19  PER   Cadillac              0.7512
  20  BOT   Cadillac              0.7784
  21  ALO   Aston Martin          0.8194
  22  STR   Aston Martin          0.8499

  =============================================
  🥇 P1: RUS (Mercedes)
  🥈 P2: ANT (Mercedes)
  🥉 P3: LEC (Ferrari)

  Best model:        Ridge
  LOO MAE:           0.0245
  LOO Std Dev:       0.0257
  Weather:           18.0°C | Rain: 10%
  =============================================

Feature coefficients (higher = more influence):
  AvgFinishNorm                +0.1194  ██
  AvgGridNorm                  +0.0783  █
  TeamScore                    -0.0253
  DNF_rate                     +0.0138
  JapanGapFromPole_s           +0.0113
  DriverPointsNorm             -0.0111
  UltimateLap_s                +0.0111
  FP2_GapToFastest_s           -0.0005
  JapanGrid                    +0.0004
  RainProbability              +0.0000
  Temperature                  +0.0000

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# ── Get predictions from all models ──────────────────────────────────────────
all_predictions = {}

for name, mdl in models.items():
    if name in ["Ridge", "ElasticNet"]:
        pipe = Pipeline([("scaler", StandardScaler()), ("model", mdl)])
    else:
        pipe = Pipeline([("model", mdl)])

    pipe.fit(X_imputed, y)
    preds = pipe.predict(X_imputed)
    ranked = pd.Series(preds, index=df["Driver"]).rank(method="min").astype(int)
    all_predictions[name] = ranked

pred_df = pd.DataFrame(all_predictions)
pred_df["BestModelPos"] = pd.Series(
    final_pipe.predict(X_imputed), index=df["Driver"]
).rank(method="min").astype(int)

pred_df = pred_df.sort_values("BestModelPos")

# ── Print all model predictions side by side ──────────────────────────────────
print("\n" + "=" * 85)
print("   PREDICTED FINISHING ORDER — 2026 JAPANESE GRAND PRIX")
print("   All models compared")
print("=" * 85)

col_w = 14
header = f"  {'DRV':<6}{'Team':<20}"
for name in models.keys():
    header += f"{name:>{col_w}}"
header += f"  {'★ Best':>{col_w}}"
print(header)
print("  " + "─" * 78)

for driver in pred_df.index:
    team = df.loc[df["Driver"] == driver, "Team"].values[0]
    row  = f"  {driver:<6}{team:<20}"
    for name in models.keys():
        pos = pred_df.loc[driver, name]
        row += f"  P{pos:<{col_w-2}}"
    best_pos = pred_df.loc[driver, "BestModelPos"]
    row += f"  P{best_pos:<{col_w-2}}"
    print(row)

# ── Podium from best model ────────────────────────────────────────────────────
best_order = pred_df.sort_values("BestModelPos")
p1 = best_order.index[0]
p2 = best_order.index[1]
p3 = best_order.index[2]

t1 = df.loc[df["Driver"] == p1, "Team"].values[0]
t2 = df.loc[df["Driver"] == p2, "Team"].values[0]
t3 = df.loc[df["Driver"] == p3, "Team"].values[0]

print(f"\n  {'='*55}")
print(f"  Best model: {best_name} (LOO MAE: {results[best_name]['MAE']:.4f})")
print(f"  🥇 P1: {p1} ({t1})")
print(f"  🥈 P2: {p2} ({t2})")
print(f"  🥉 P3: {p3} ({t3})")
print(f"  Weather: {df['Temperature'].iloc[0]:.1f}°C | Rain: {df['RainProbability'].iloc[0]:.0%}")
print(f"  {'='*55}")

# ── Consensus podium ──────────────────────────────────────────────────────────
print("\n  CONSENSUS PODIUM (across all models):")
print("  " + "─" * 35)
medals = ["🥇", "🥈", "🥉"]
for pos in [1, 2, 3]:
    pos_counts = {}
    for name in models.keys():
        drivers_at_pos = pred_df[pred_df[name] == pos].index.tolist()
        for d in drivers_at_pos:
            pos_counts[d] = pos_counts.get(d, 0) + 1
    if pos_counts:
        top   = max(pos_counts, key=pos_counts.get)
        votes = pos_counts[top]
        print(f"  {medals[pos-1]} P{pos}: {top} — {votes}/{len(models)} models agree")
print(f"  {'='*55}")

=====================================================================================
   PREDICTED FINISHING ORDER — 2026 JAPANESE GRAND PRIX
   All models compared
=====================================================================================
  DRV   Team                         Ridge    ElasticNet  RandomForest GradientBoost       XGBoost          ★ Best
  ──────────────────────────────────────────────────────────────────────────────
  RUS   Mercedes              P1             P2             P1             P2             P1             P1
  ANT   Mercedes              P2             P1             P1             P1             P1             P2
  LEC   Ferrari               P3             P3             P1             P3             P3             P3
  HAM   Ferrari               P4             P4             P4             P4             P4             P4
  GAS   Alpine                P5             P6             P5             P5             P5             P5
  BEA   Haas                  P6             P5             P6             P6             P6             P6
  NOR   McLaren               P7             P7             P7             P7             P7             P7
  LAW   Racing Bulls          P8             P8             P8             P8             P8             P8
  LIN   Racing Bulls          P9             P9             P9             P9             P9             P9
  HAD   Red Bull              P10            P10            P10            P10            P10            P10
  OCO   Haas                  P11            P12            P12            P11            P11            P11
  VER   Red Bull              P12            P11            P11            P12            P12            P12
  COL   Alpine                P13            P13            P13            P13            P13            P13
  BOR   Audi                  P14            P14            P16            P14            P15            P14
  PIA   McLaren               P15            P17            P14            P17            P14            P15
  SAI   Williams              P16            P15            P15            P15            P16            P16
  HUL   Audi                  P17            P16            P17            P16            P17            P17
  ALB   Williams              P18            P18            P18            P18            P18            P18
  PER   Cadillac              P19            P19            P20            P19            P20            P19
  BOT   Cadillac              P20            P20            P22            P19            P19            P20
  ALO   Aston Martin          P21            P21            P21            P21            P21            P21
  STR   Aston Martin          P22            P22            P19            P22            P22            P22

  =======================================================
  Best model: Ridge (LOO MAE: 0.0245)
  🥇 P1: RUS (Mercedes)
  🥈 P2: ANT (Mercedes)
  🥉 P3: LEC (Ferrari)
  Weather: 18.0°C | Rain: 10%
  =======================================================

  CONSENSUS PODIUM (across all models):
  ───────────────────────────────────
  🥇 P1: ANT — 4/5 models agree
  🥈 P2: RUS — 2/5 models agree
  🥉 P3: LEC — 4/5 models agree
  =======================================================